// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_persisted_tab_data.proto

package org.chromium.chrome.browser.tab.proto;

public final class ShoppingPersistedTabData {
  private ShoppingPersistedTabData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ShoppingPersistedTabDataProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     * @return Whether the priceMicros field is set.
     */
    boolean hasPriceMicros();
    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     * @return The priceMicros.
     */
    long getPriceMicros();

    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     * @return Whether the previousPriceMicros field is set.
     */
    boolean hasPreviousPriceMicros();
    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     * @return The previousPriceMicros.
     */
    long getPreviousPriceMicros();

    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return Whether the priceCurrencyCode field is set.
     */
    boolean hasPriceCurrencyCode();
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return The priceCurrencyCode.
     */
    java.lang.String getPriceCurrencyCode();
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return The bytes for priceCurrencyCode.
     */
    com.google.protobuf.ByteString
        getPriceCurrencyCodeBytes();

    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     * @return Whether the lastUpdatedMs field is set.
     */
    boolean hasLastUpdatedMs();
    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     * @return The lastUpdatedMs.
     */
    long getLastUpdatedMs();

    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     * @return Whether the lastPriceChangeTimeMs field is set.
     */
    boolean hasLastPriceChangeTimeMs();
    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     * @return The lastPriceChangeTimeMs.
     */
    long getLastPriceChangeTimeMs();

    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return Whether the mainOfferId field is set.
     */
    boolean hasMainOfferId();
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return The mainOfferId.
     */
    java.lang.String getMainOfferId();
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return The bytes for mainOfferId.
     */
    com.google.protobuf.ByteString
        getMainOfferIdBytes();

    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return Whether the serializedGurl field is set.
     */
    boolean hasSerializedGurl();
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return The serializedGurl.
     */
    java.lang.String getSerializedGurl();
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return The bytes for serializedGurl.
     */
    com.google.protobuf.ByteString
        getSerializedGurlBytes();

    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     * @return Whether the isCurrentPriceDropSeen field is set.
     */
    boolean hasIsCurrentPriceDropSeen();
    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     * @return The isCurrentPriceDropSeen.
     */
    boolean getIsCurrentPriceDropSeen();
  }
  /**
   * Protobuf type {@code org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto}
   */
  public  static final class ShoppingPersistedTabDataProto extends
      com.google.protobuf.GeneratedMessageLite<
          ShoppingPersistedTabDataProto, ShoppingPersistedTabDataProto.Builder> implements
      // @@protoc_insertion_point(message_implements:org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto)
      ShoppingPersistedTabDataProtoOrBuilder {
    private ShoppingPersistedTabDataProto() {
      priceCurrencyCode_ = "";
      mainOfferId_ = "";
      serializedGurl_ = "";
    }
    private int bitField0_;
    public static final int PRICE_MICROS_FIELD_NUMBER = 1;
    private long priceMicros_;
    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     * @return Whether the priceMicros field is set.
     */
    @java.lang.Override
    public boolean hasPriceMicros() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     * @return The priceMicros.
     */
    @java.lang.Override
    public long getPriceMicros() {
      return priceMicros_;
    }
    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     * @param value The priceMicros to set.
     */
    private void setPriceMicros(long value) {
      bitField0_ |= 0x00000001;
      priceMicros_ = value;
    }
    /**
     * <pre>
     * String representing the price of the offer.
     * </pre>
     *
     * <code>optional int64 price_micros = 1;</code>
     */
    private void clearPriceMicros() {
      bitField0_ = (bitField0_ & ~0x00000001);
      priceMicros_ = 0L;
    }

    public static final int PREVIOUS_PRICE_MICROS_FIELD_NUMBER = 2;
    private long previousPriceMicros_;
    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     * @return Whether the previousPriceMicros field is set.
     */
    @java.lang.Override
    public boolean hasPreviousPriceMicros() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     * @return The previousPriceMicros.
     */
    @java.lang.Override
    public long getPreviousPriceMicros() {
      return previousPriceMicros_;
    }
    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     * @param value The previousPriceMicros to set.
     */
    private void setPreviousPriceMicros(long value) {
      bitField0_ |= 0x00000002;
      previousPriceMicros_ = value;
    }
    /**
     * <pre>
     * String representing previous price of the offer.
     * </pre>
     *
     * <code>optional int64 previous_price_micros = 2;</code>
     */
    private void clearPreviousPriceMicros() {
      bitField0_ = (bitField0_ & ~0x00000002);
      previousPriceMicros_ = 0L;
    }

    public static final int PRICE_CURRENCY_CODE_FIELD_NUMBER = 3;
    private java.lang.String priceCurrencyCode_;
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return Whether the priceCurrencyCode field is set.
     */
    @java.lang.Override
    public boolean hasPriceCurrencyCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return The priceCurrencyCode.
     */
    @java.lang.Override
    public java.lang.String getPriceCurrencyCode() {
      return priceCurrencyCode_;
    }
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @return The bytes for priceCurrencyCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceCurrencyCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(priceCurrencyCode_);
    }
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @param value The priceCurrencyCode to set.
     */
    private void setPriceCurrencyCode(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      priceCurrencyCode_ = value;
    }
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     */
    private void clearPriceCurrencyCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      priceCurrencyCode_ = getDefaultInstance().getPriceCurrencyCode();
    }
    /**
     * <pre>
     * Currency code of the price.
     * </pre>
     *
     * <code>optional string price_currency_code = 3;</code>
     * @param value The bytes for priceCurrencyCode to set.
     */
    private void setPriceCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      priceCurrencyCode_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int LAST_UPDATED_MS_FIELD_NUMBER = 4;
    private long lastUpdatedMs_;
    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     * @return Whether the lastUpdatedMs field is set.
     */
    @java.lang.Override
    public boolean hasLastUpdatedMs() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     * @return The lastUpdatedMs.
     */
    @java.lang.Override
    public long getLastUpdatedMs() {
      return lastUpdatedMs_;
    }
    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     * @param value The lastUpdatedMs to set.
     */
    private void setLastUpdatedMs(long value) {
      bitField0_ |= 0x00000008;
      lastUpdatedMs_ = value;
    }
    /**
     * <pre>
     * Time the ShoppingPersistedTabData was fetched
     * measured in the number of seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_updated_ms = 4;</code>
     */
    private void clearLastUpdatedMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastUpdatedMs_ = 0L;
    }

    public static final int LAST_PRICE_CHANGE_TIME_MS_FIELD_NUMBER = 5;
    private long lastPriceChangeTimeMs_;
    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     * @return Whether the lastPriceChangeTimeMs field is set.
     */
    @java.lang.Override
    public boolean hasLastPriceChangeTimeMs() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     * @return The lastPriceChangeTimeMs.
     */
    @java.lang.Override
    public long getLastPriceChangeTimeMs() {
      return lastPriceChangeTimeMs_;
    }
    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     * @param value The lastPriceChangeTimeMs to set.
     */
    private void setLastPriceChangeTimeMs(long value) {
      bitField0_ |= 0x00000010;
      lastPriceChangeTimeMs_ = value;
    }
    /**
     * <pre>
     * Time the price changed measured in the number of
     * seconds since the epoch.
     * </pre>
     *
     * <code>optional int64 last_price_change_time_ms = 5;</code>
     */
    private void clearLastPriceChangeTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastPriceChangeTimeMs_ = 0L;
    }

    public static final int MAIN_OFFER_ID_FIELD_NUMBER = 6;
    private java.lang.String mainOfferId_;
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return Whether the mainOfferId field is set.
     */
    @java.lang.Override
    public boolean hasMainOfferId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return The mainOfferId.
     */
    @java.lang.Override
    public java.lang.String getMainOfferId() {
      return mainOfferId_;
    }
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @return The bytes for mainOfferId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMainOfferIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mainOfferId_);
    }
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @param value The mainOfferId to set.
     */
    private void setMainOfferId(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000020;
      mainOfferId_ = value;
    }
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     */
    private void clearMainOfferId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      mainOfferId_ = getDefaultInstance().getMainOfferId();
    }
    /**
     * <pre>
     * The id of the main offer on the page.
     * </pre>
     *
     * <code>optional string main_offer_id = 6;</code>
     * @param value The bytes for mainOfferId to set.
     */
    private void setMainOfferIdBytes(
        com.google.protobuf.ByteString value) {
      mainOfferId_ = value.toStringUtf8();
      bitField0_ |= 0x00000020;
    }

    public static final int SERIALIZED_GURL_FIELD_NUMBER = 7;
    private java.lang.String serializedGurl_;
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return Whether the serializedGurl field is set.
     */
    @java.lang.Override
    public boolean hasSerializedGurl() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return The serializedGurl.
     */
    @java.lang.Override
    public java.lang.String getSerializedGurl() {
      return serializedGurl_;
    }
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @return The bytes for serializedGurl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSerializedGurlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serializedGurl_);
    }
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @param value The serializedGurl to set.
     */
    private void setSerializedGurl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000040;
      serializedGurl_ = value;
    }
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     */
    private void clearSerializedGurl() {
      bitField0_ = (bitField0_ & ~0x00000040);
      serializedGurl_ = getDefaultInstance().getSerializedGurl();
    }
    /**
     * <pre>
     * The gurl associated with the price drop.
     * </pre>
     *
     * <code>optional string serialized_gurl = 7;</code>
     * @param value The bytes for serializedGurl to set.
     */
    private void setSerializedGurlBytes(
        com.google.protobuf.ByteString value) {
      serializedGurl_ = value.toStringUtf8();
      bitField0_ |= 0x00000040;
    }

    public static final int IS_CURRENT_PRICE_DROP_SEEN_FIELD_NUMBER = 8;
    private boolean isCurrentPriceDropSeen_;
    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     * @return Whether the isCurrentPriceDropSeen field is set.
     */
    @java.lang.Override
    public boolean hasIsCurrentPriceDropSeen() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     * @return The isCurrentPriceDropSeen.
     */
    @java.lang.Override
    public boolean getIsCurrentPriceDropSeen() {
      return isCurrentPriceDropSeen_;
    }
    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     * @param value The isCurrentPriceDropSeen to set.
     */
    private void setIsCurrentPriceDropSeen(boolean value) {
      bitField0_ |= 0x00000080;
      isCurrentPriceDropSeen_ = value;
    }
    /**
     * <pre>
     * Whether the user has seen the current price drop in the tab switcher grid.
     * </pre>
     *
     * <code>optional bool is_current_price_drop_seen = 8;</code>
     */
    private void clearIsCurrentPriceDropSeen() {
      bitField0_ = (bitField0_ & ~0x00000080);
      isCurrentPriceDropSeen_ = false;
    }

    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto)
        org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProtoOrBuilder {
      // Construct using org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * String representing the price of the offer.
       * </pre>
       *
       * <code>optional int64 price_micros = 1;</code>
       * @return Whether the priceMicros field is set.
       */
      @java.lang.Override
      public boolean hasPriceMicros() {
        return instance.hasPriceMicros();
      }
      /**
       * <pre>
       * String representing the price of the offer.
       * </pre>
       *
       * <code>optional int64 price_micros = 1;</code>
       * @return The priceMicros.
       */
      @java.lang.Override
      public long getPriceMicros() {
        return instance.getPriceMicros();
      }
      /**
       * <pre>
       * String representing the price of the offer.
       * </pre>
       *
       * <code>optional int64 price_micros = 1;</code>
       * @param value The priceMicros to set.
       * @return This builder for chaining.
       */
      public Builder setPriceMicros(long value) {
        copyOnWrite();
        instance.setPriceMicros(value);
        return this;
      }
      /**
       * <pre>
       * String representing the price of the offer.
       * </pre>
       *
       * <code>optional int64 price_micros = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceMicros() {
        copyOnWrite();
        instance.clearPriceMicros();
        return this;
      }

      /**
       * <pre>
       * String representing previous price of the offer.
       * </pre>
       *
       * <code>optional int64 previous_price_micros = 2;</code>
       * @return Whether the previousPriceMicros field is set.
       */
      @java.lang.Override
      public boolean hasPreviousPriceMicros() {
        return instance.hasPreviousPriceMicros();
      }
      /**
       * <pre>
       * String representing previous price of the offer.
       * </pre>
       *
       * <code>optional int64 previous_price_micros = 2;</code>
       * @return The previousPriceMicros.
       */
      @java.lang.Override
      public long getPreviousPriceMicros() {
        return instance.getPreviousPriceMicros();
      }
      /**
       * <pre>
       * String representing previous price of the offer.
       * </pre>
       *
       * <code>optional int64 previous_price_micros = 2;</code>
       * @param value The previousPriceMicros to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousPriceMicros(long value) {
        copyOnWrite();
        instance.setPreviousPriceMicros(value);
        return this;
      }
      /**
       * <pre>
       * String representing previous price of the offer.
       * </pre>
       *
       * <code>optional int64 previous_price_micros = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousPriceMicros() {
        copyOnWrite();
        instance.clearPreviousPriceMicros();
        return this;
      }

      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @return Whether the priceCurrencyCode field is set.
       */
      @java.lang.Override
      public boolean hasPriceCurrencyCode() {
        return instance.hasPriceCurrencyCode();
      }
      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @return The priceCurrencyCode.
       */
      @java.lang.Override
      public java.lang.String getPriceCurrencyCode() {
        return instance.getPriceCurrencyCode();
      }
      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @return The bytes for priceCurrencyCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPriceCurrencyCodeBytes() {
        return instance.getPriceCurrencyCodeBytes();
      }
      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @param value The priceCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setPriceCurrencyCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setPriceCurrencyCode(value);
        return this;
      }
      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceCurrencyCode() {
        copyOnWrite();
        instance.clearPriceCurrencyCode();
        return this;
      }
      /**
       * <pre>
       * Currency code of the price.
       * </pre>
       *
       * <code>optional string price_currency_code = 3;</code>
       * @param value The bytes for priceCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setPriceCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPriceCurrencyCodeBytes(value);
        return this;
      }

      /**
       * <pre>
       * Time the ShoppingPersistedTabData was fetched
       * measured in the number of seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_updated_ms = 4;</code>
       * @return Whether the lastUpdatedMs field is set.
       */
      @java.lang.Override
      public boolean hasLastUpdatedMs() {
        return instance.hasLastUpdatedMs();
      }
      /**
       * <pre>
       * Time the ShoppingPersistedTabData was fetched
       * measured in the number of seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_updated_ms = 4;</code>
       * @return The lastUpdatedMs.
       */
      @java.lang.Override
      public long getLastUpdatedMs() {
        return instance.getLastUpdatedMs();
      }
      /**
       * <pre>
       * Time the ShoppingPersistedTabData was fetched
       * measured in the number of seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_updated_ms = 4;</code>
       * @param value The lastUpdatedMs to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdatedMs(long value) {
        copyOnWrite();
        instance.setLastUpdatedMs(value);
        return this;
      }
      /**
       * <pre>
       * Time the ShoppingPersistedTabData was fetched
       * measured in the number of seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_updated_ms = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdatedMs() {
        copyOnWrite();
        instance.clearLastUpdatedMs();
        return this;
      }

      /**
       * <pre>
       * Time the price changed measured in the number of
       * seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_price_change_time_ms = 5;</code>
       * @return Whether the lastPriceChangeTimeMs field is set.
       */
      @java.lang.Override
      public boolean hasLastPriceChangeTimeMs() {
        return instance.hasLastPriceChangeTimeMs();
      }
      /**
       * <pre>
       * Time the price changed measured in the number of
       * seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_price_change_time_ms = 5;</code>
       * @return The lastPriceChangeTimeMs.
       */
      @java.lang.Override
      public long getLastPriceChangeTimeMs() {
        return instance.getLastPriceChangeTimeMs();
      }
      /**
       * <pre>
       * Time the price changed measured in the number of
       * seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_price_change_time_ms = 5;</code>
       * @param value The lastPriceChangeTimeMs to set.
       * @return This builder for chaining.
       */
      public Builder setLastPriceChangeTimeMs(long value) {
        copyOnWrite();
        instance.setLastPriceChangeTimeMs(value);
        return this;
      }
      /**
       * <pre>
       * Time the price changed measured in the number of
       * seconds since the epoch.
       * </pre>
       *
       * <code>optional int64 last_price_change_time_ms = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastPriceChangeTimeMs() {
        copyOnWrite();
        instance.clearLastPriceChangeTimeMs();
        return this;
      }

      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @return Whether the mainOfferId field is set.
       */
      @java.lang.Override
      public boolean hasMainOfferId() {
        return instance.hasMainOfferId();
      }
      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @return The mainOfferId.
       */
      @java.lang.Override
      public java.lang.String getMainOfferId() {
        return instance.getMainOfferId();
      }
      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @return The bytes for mainOfferId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMainOfferIdBytes() {
        return instance.getMainOfferIdBytes();
      }
      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @param value The mainOfferId to set.
       * @return This builder for chaining.
       */
      public Builder setMainOfferId(
          java.lang.String value) {
        copyOnWrite();
        instance.setMainOfferId(value);
        return this;
      }
      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMainOfferId() {
        copyOnWrite();
        instance.clearMainOfferId();
        return this;
      }
      /**
       * <pre>
       * The id of the main offer on the page.
       * </pre>
       *
       * <code>optional string main_offer_id = 6;</code>
       * @param value The bytes for mainOfferId to set.
       * @return This builder for chaining.
       */
      public Builder setMainOfferIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMainOfferIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @return Whether the serializedGurl field is set.
       */
      @java.lang.Override
      public boolean hasSerializedGurl() {
        return instance.hasSerializedGurl();
      }
      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @return The serializedGurl.
       */
      @java.lang.Override
      public java.lang.String getSerializedGurl() {
        return instance.getSerializedGurl();
      }
      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @return The bytes for serializedGurl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSerializedGurlBytes() {
        return instance.getSerializedGurlBytes();
      }
      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @param value The serializedGurl to set.
       * @return This builder for chaining.
       */
      public Builder setSerializedGurl(
          java.lang.String value) {
        copyOnWrite();
        instance.setSerializedGurl(value);
        return this;
      }
      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializedGurl() {
        copyOnWrite();
        instance.clearSerializedGurl();
        return this;
      }
      /**
       * <pre>
       * The gurl associated with the price drop.
       * </pre>
       *
       * <code>optional string serialized_gurl = 7;</code>
       * @param value The bytes for serializedGurl to set.
       * @return This builder for chaining.
       */
      public Builder setSerializedGurlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSerializedGurlBytes(value);
        return this;
      }

      /**
       * <pre>
       * Whether the user has seen the current price drop in the tab switcher grid.
       * </pre>
       *
       * <code>optional bool is_current_price_drop_seen = 8;</code>
       * @return Whether the isCurrentPriceDropSeen field is set.
       */
      @java.lang.Override
      public boolean hasIsCurrentPriceDropSeen() {
        return instance.hasIsCurrentPriceDropSeen();
      }
      /**
       * <pre>
       * Whether the user has seen the current price drop in the tab switcher grid.
       * </pre>
       *
       * <code>optional bool is_current_price_drop_seen = 8;</code>
       * @return The isCurrentPriceDropSeen.
       */
      @java.lang.Override
      public boolean getIsCurrentPriceDropSeen() {
        return instance.getIsCurrentPriceDropSeen();
      }
      /**
       * <pre>
       * Whether the user has seen the current price drop in the tab switcher grid.
       * </pre>
       *
       * <code>optional bool is_current_price_drop_seen = 8;</code>
       * @param value The isCurrentPriceDropSeen to set.
       * @return This builder for chaining.
       */
      public Builder setIsCurrentPriceDropSeen(boolean value) {
        copyOnWrite();
        instance.setIsCurrentPriceDropSeen(value);
        return this;
      }
      /**
       * <pre>
       * Whether the user has seen the current price drop in the tab switcher grid.
       * </pre>
       *
       * <code>optional bool is_current_price_drop_seen = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsCurrentPriceDropSeen() {
        copyOnWrite();
        instance.clearIsCurrentPriceDropSeen();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "priceMicros_",
              "previousPriceMicros_",
              "priceCurrencyCode_",
              "lastUpdatedMs_",
              "lastPriceChangeTimeMs_",
              "mainOfferId_",
              "serializedGurl_",
              "isCurrentPriceDropSeen_",
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u1002\u0000\u0002\u1002\u0001" +
                "\u0003\u1008\u0002\u0004\u1002\u0003\u0005\u1002\u0004\u0006\u1008\u0005\u0007\u1008" +
                "\u0006\b\u1007\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabDataProto)
    private static final org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto DEFAULT_INSTANCE;
    static {
      ShoppingPersistedTabDataProto defaultInstance = new ShoppingPersistedTabDataProto();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ShoppingPersistedTabDataProto.class, defaultInstance);
    }

    public static org.chromium.chrome.browser.tab.proto.ShoppingPersistedTabData.ShoppingPersistedTabDataProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ShoppingPersistedTabDataProto> PARSER;

    public static com.google.protobuf.Parser<ShoppingPersistedTabDataProto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
