// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store_persisted_tab_data.proto

package org.chromium.chrome.browser.tab.proto;

public final class StorePersistedTabData {
  private StorePersistedTabData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface StorePersistedTabDataProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     * @return Whether the openingTime field is set.
     */
    boolean hasOpeningTime();
    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     * @return The openingTime.
     */
    int getOpeningTime();

    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     * @return Whether the closingTime field is set.
     */
    boolean hasClosingTime();
    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     * @return The closingTime.
     */
    int getClosingTime();
  }
  /**
   * Protobuf type {@code org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto}
   */
  public  static final class StorePersistedTabDataProto extends
      com.google.protobuf.GeneratedMessageLite<
          StorePersistedTabDataProto, StorePersistedTabDataProto.Builder> implements
      // @@protoc_insertion_point(message_implements:org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto)
      StorePersistedTabDataProtoOrBuilder {
    private StorePersistedTabDataProto() {
    }
    private int bitField0_;
    public static final int OPENING_TIME_FIELD_NUMBER = 1;
    private int openingTime_;
    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     * @return Whether the openingTime field is set.
     */
    @java.lang.Override
    public boolean hasOpeningTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     * @return The openingTime.
     */
    @java.lang.Override
    public int getOpeningTime() {
      return openingTime_;
    }
    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     * @param value The openingTime to set.
     */
    private void setOpeningTime(int value) {
      bitField0_ |= 0x00000001;
      openingTime_ = value;
    }
    /**
     * <pre>
     * int representing opening time in military minutes (ISO 8601 hhmm).
     * https://en.wikipedia.org/wiki/ISO_8601
     * </pre>
     *
     * <code>optional int32 opening_time = 1;</code>
     */
    private void clearOpeningTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      openingTime_ = 0;
    }

    public static final int CLOSING_TIME_FIELD_NUMBER = 2;
    private int closingTime_;
    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     * @return Whether the closingTime field is set.
     */
    @java.lang.Override
    public boolean hasClosingTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     * @return The closingTime.
     */
    @java.lang.Override
    public int getClosingTime() {
      return closingTime_;
    }
    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     * @param value The closingTime to set.
     */
    private void setClosingTime(int value) {
      bitField0_ |= 0x00000002;
      closingTime_ = value;
    }
    /**
     * <pre>
     * int representing closing time in military minutes (ISO 8601 hhmm).
     * </pre>
     *
     * <code>optional int32 closing_time = 2;</code>
     */
    private void clearClosingTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      closingTime_ = 0;
    }

    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto)
        org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProtoOrBuilder {
      // Construct using org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * int representing opening time in military minutes (ISO 8601 hhmm).
       * https://en.wikipedia.org/wiki/ISO_8601
       * </pre>
       *
       * <code>optional int32 opening_time = 1;</code>
       * @return Whether the openingTime field is set.
       */
      @java.lang.Override
      public boolean hasOpeningTime() {
        return instance.hasOpeningTime();
      }
      /**
       * <pre>
       * int representing opening time in military minutes (ISO 8601 hhmm).
       * https://en.wikipedia.org/wiki/ISO_8601
       * </pre>
       *
       * <code>optional int32 opening_time = 1;</code>
       * @return The openingTime.
       */
      @java.lang.Override
      public int getOpeningTime() {
        return instance.getOpeningTime();
      }
      /**
       * <pre>
       * int representing opening time in military minutes (ISO 8601 hhmm).
       * https://en.wikipedia.org/wiki/ISO_8601
       * </pre>
       *
       * <code>optional int32 opening_time = 1;</code>
       * @param value The openingTime to set.
       * @return This builder for chaining.
       */
      public Builder setOpeningTime(int value) {
        copyOnWrite();
        instance.setOpeningTime(value);
        return this;
      }
      /**
       * <pre>
       * int representing opening time in military minutes (ISO 8601 hhmm).
       * https://en.wikipedia.org/wiki/ISO_8601
       * </pre>
       *
       * <code>optional int32 opening_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpeningTime() {
        copyOnWrite();
        instance.clearOpeningTime();
        return this;
      }

      /**
       * <pre>
       * int representing closing time in military minutes (ISO 8601 hhmm).
       * </pre>
       *
       * <code>optional int32 closing_time = 2;</code>
       * @return Whether the closingTime field is set.
       */
      @java.lang.Override
      public boolean hasClosingTime() {
        return instance.hasClosingTime();
      }
      /**
       * <pre>
       * int representing closing time in military minutes (ISO 8601 hhmm).
       * </pre>
       *
       * <code>optional int32 closing_time = 2;</code>
       * @return The closingTime.
       */
      @java.lang.Override
      public int getClosingTime() {
        return instance.getClosingTime();
      }
      /**
       * <pre>
       * int representing closing time in military minutes (ISO 8601 hhmm).
       * </pre>
       *
       * <code>optional int32 closing_time = 2;</code>
       * @param value The closingTime to set.
       * @return This builder for chaining.
       */
      public Builder setClosingTime(int value) {
        copyOnWrite();
        instance.setClosingTime(value);
        return this;
      }
      /**
       * <pre>
       * int representing closing time in military minutes (ISO 8601 hhmm).
       * </pre>
       *
       * <code>optional int32 closing_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClosingTime() {
        copyOnWrite();
        instance.clearClosingTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "openingTime_",
              "closingTime_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
                "\u1004\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.chromium.chrome.browser.tab.proto.StorePersistedTabDataProto)
    private static final org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto DEFAULT_INSTANCE;
    static {
      StorePersistedTabDataProto defaultInstance = new StorePersistedTabDataProto();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        StorePersistedTabDataProto.class, defaultInstance);
    }

    public static org.chromium.chrome.browser.tab.proto.StorePersistedTabData.StorePersistedTabDataProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StorePersistedTabDataProto> PARSER;

    public static com.google.protobuf.Parser<StorePersistedTabDataProto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
