// AdAuctionService.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/interest_group/ad_auction_service.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface AdAuctionService extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends AdAuctionService, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<AdAuctionService, AdAuctionService.Proxy> MANAGER = AdAuctionService_Internal.MANAGER;

    void createAdRequest(
AdRequestConfig config, 
CreateAdRequest_Response callback);

    interface CreateAdRequest_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<String> { }


    void finalizeAd(
String adsGuid, AuctionAdConfig config, 
FinalizeAd_Response callback);

    interface FinalizeAd_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.url.mojom.Url> { }


    void runAdAuction(
AuctionAdConfig config, 
RunAdAuction_Response callback);

    interface RunAdAuction_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.url.mojom.Url> { }


    void joinInterestGroup(
InterestGroup group, 
JoinInterestGroup_Response callback);

    interface JoinInterestGroup_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


    void leaveInterestGroup(
org.chromium.url.internal.mojom.Origin owner, String name, 
LeaveInterestGroup_Response callback);

    interface LeaveInterestGroup_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


    void leaveInterestGroupForDocument(
);


    void updateAdInterestGroups(
);


    void deprecatedGetUrlFromUrn(
org.chromium.url.mojom.Url uuidUrl, 
DeprecatedGetUrlFromUrn_Response callback);

    interface DeprecatedGetUrlFromUrn_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.url.mojom.Url> { }


    void deprecatedReplaceInUrn(
org.chromium.url.mojom.Url uuidUrl, Replacement[] replacements, 
DeprecatedReplaceInUrn_Response callback);

    interface DeprecatedReplaceInUrn_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


}
