// CrosWindowManagementFactory.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/chromeos/system_extensions/window_management/cros_window_management.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface CrosWindowManagementFactory extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends CrosWindowManagementFactory, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<CrosWindowManagementFactory, CrosWindowManagementFactory.Proxy> MANAGER = CrosWindowManagementFactory_Internal.MANAGER;

    void create(
org.chromium.mojo.bindings.AssociatedInterfaceRequestNotSupported receiver, org.chromium.mojo.bindings.AssociatedInterfaceNotSupported observerRemote);


}
