// IframeAttributes.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/frame/frame.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public final class IframeAttributes extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 48;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(48, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public org.chromium.network.mojom.ContentSecurityPolicy parsedCspAttribute;
    public boolean anonymous;
    public String id;
    public String name;
    public String src;

    private IframeAttributes(int version) {
        super(STRUCT_SIZE, version);
    }

    public IframeAttributes() {
        this(0);
    }

    public static IframeAttributes deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static IframeAttributes deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static IframeAttributes decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        IframeAttributes result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new IframeAttributes(elementsOrVersion);
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, true);
                result.parsedCspAttribute = org.chromium.network.mojom.ContentSecurityPolicy.decode(decoder1);
                }
                {
                    
                result.anonymous = decoder0.readBoolean(16, 0);
                }
                {
                    
                result.id = decoder0.readString(24, false);
                }
                {
                    
                result.name = decoder0.readString(32, false);
                }
                {
                    
                result.src = decoder0.readString(40, false);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.parsedCspAttribute, 8, true);
        
        encoder0.encode(this.anonymous, 16, 0);
        
        encoder0.encode(this.id, 24, false);
        
        encoder0.encode(this.name, 32, false);
        
        encoder0.encode(this.src, 40, false);
    }
}