// PressureServiceConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/compute_pressure/pressure_service.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class PressureServiceConstants {


    
    public static final int MAX_PRESSURE_CPU_UTILIZATION_THRESHOLDS = (int) 3;



    private PressureServiceConstants() {}

}