// SubAppsServiceAddResultCode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/subapps/sub_apps_service.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class SubAppsServiceAddResultCode {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        SubAppsServiceAddResultCode.SUCCESS_NEW_INSTALL,
        SubAppsServiceAddResultCode.SUCCESS_ALREADY_INSTALLED,
        SubAppsServiceAddResultCode.USER_INSTALL_DECLINED,
        SubAppsServiceAddResultCode.EXPECTED_APP_ID_CHECK_FAILED,
        SubAppsServiceAddResultCode.PARENT_APP_UNINSTALLED,
        SubAppsServiceAddResultCode.FAILURE})
    public @interface EnumType {}

    public static final int SUCCESS_NEW_INSTALL = 0;
    public static final int SUCCESS_ALREADY_INSTALLED = 1;
    public static final int USER_INSTALL_DECLINED = 2;
    public static final int EXPECTED_APP_ID_CHECK_FAILED = 3;
    public static final int PARENT_APP_UNINSTALLED = 4;
    public static final int FAILURE = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private SubAppsServiceAddResultCode() {}
}