
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/feed/core/v2/public/common_enums.h

package org.chromium.chrome.browser.feed.v2;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    FeedUserActionType.TAPPED_ON_CARD, FeedUserActionType.SHOWN_CARD_DEPRECATED,
    FeedUserActionType.TAPPED_SEND_FEEDBACK, FeedUserActionType.TAPPED_LEARN_MORE,
    FeedUserActionType.TAPPED_HIDE_STORY, FeedUserActionType.TAPPED_NOT_INTERESTED_IN,
    FeedUserActionType.TAPPED_MANAGE_INTERESTS, FeedUserActionType.TAPPED_DOWNLOAD,
    FeedUserActionType.TAPPED_OPEN_IN_NEW_TAB, FeedUserActionType.OPENED_CONTEXT_MENU,
    FeedUserActionType.OPENED_FEED_SURFACE, FeedUserActionType.TAPPED_OPEN_IN_NEW_INCOGNITO_TAB,
    FeedUserActionType.EPHEMERAL_CHANGE, FeedUserActionType.EPHEMERAL_CHANGE_REJECTED,
    FeedUserActionType.TAPPED_TURN_ON, FeedUserActionType.TAPPED_TURN_OFF,
    FeedUserActionType.TAPPED_MANAGE_ACTIVITY, FeedUserActionType.ADDED_TO_READ_LATER,
    FeedUserActionType.CLOSED_CONTEXT_MENU, FeedUserActionType.EPHEMERAL_CHANGE_COMMITED,
    FeedUserActionType.OPENED_DIALOG, FeedUserActionType.CLOSED_DIALOG,
    FeedUserActionType.SHOW_SNACKBAR, FeedUserActionType.OPENED_NATIVE_ACTION_SHEET,
    FeedUserActionType.OPENED_NATIVE_CONTEXT_MENU, FeedUserActionType.CLOSED_NATIVE_CONTEXT_MENU,
    FeedUserActionType.OPENED_NATIVE_PULLDOWN_MENU, FeedUserActionType.CLOSED_NATIVE_PULLDOWN_MENU,
    FeedUserActionType.TAPPED_MANAGE_REACTIONS, FeedUserActionType.SHARE,
    FeedUserActionType.TAPPED_MANAGE_FOLLOWING,
    FeedUserActionType.TAPPED_FOLLOW_ON_MANAGEMENT_SURFACE,
    FeedUserActionType.TAPPED_UNFOLLOW_ON_MANAGEMENT_SURFACE,
    FeedUserActionType.TAPPED_FOLLOW_ON_FOLLOW_ACCELERATOR,
    FeedUserActionType.TAPPED_FOLLOW_TRY_AGAIN_ON_SNACKBAR,
    FeedUserActionType.TAPPED_REFOLLOW_AFTER_UNFOLLOW_ON_SNACKBAR,
    FeedUserActionType.TAPPED_UNFOLLOW_TRY_AGAIN_ON_SNACKBAR,
    FeedUserActionType.TAPPED_GO_TO_FEED_POST_FOLLOW_ACTIVE_HELP,
    FeedUserActionType.TAPPED_DISMISS_POST_FOLLOW_ACTIVE_HELP,
    FeedUserActionType.TAPPED_DISCOVER_FEED_PREVIEW, FeedUserActionType.OPENED_AUTOPLAY_SETTINGS,
    FeedUserActionType.TAPPED_ADD_TO_READING_LIST, FeedUserActionType.TAPPED_MANAGE,
    FeedUserActionType.TAPPED_MANAGE_HIDDEN, FeedUserActionType.TAPPED_FOLLOW_BUTTON,
    FeedUserActionType.DISCOVER_FEED_SELECTED, FeedUserActionType.FOLLOWING_FEED_SELECTED,
    FeedUserActionType.TAPPED_UNFOLLOW_BUTTON, FeedUserActionType.SHOW_FOLLOW_SUCCEED_SNACKBAR,
    FeedUserActionType.SHOW_FOLLOW_FAILED_SNACKBAR,
    FeedUserActionType.SHOW_UNFOLLOW_SUCCEED_SNACKBAR,
    FeedUserActionType.SHOW_UNFOLLOW_FAILED_SNACKBAR,
    FeedUserActionType.TAPPED_GO_TO_FEED_ON_SNACKBAR, FeedUserActionType.TAPPED_CROW_BUTTON,
    FeedUserActionType.FIRST_FOLLOW_SHEET_SHOWN,
    FeedUserActionType.FIRST_FOLLOW_SHEET_TAPPED_GO_TO_FEED,
    FeedUserActionType.FIRST_FOLLOW_SHEET_TAPPED_GOT_IT,
    FeedUserActionType.FOLLOW_RECOMMENDATION_IPH_SHOWN,
    FeedUserActionType.TAPPED_OPEN_IN_NEW_TAB_IN_GROUP, FeedUserActionType.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface FeedUserActionType {
  /**
   * User tapped on card, opening the article in the same tab.
   */
  int TAPPED_ON_CARD = 0;
  /**
   * DEPRECATED: This was never reported.
   */
  int SHOWN_CARD_DEPRECATED = 1;
  /**
   * User tapped on 'Send Feedback' in the back of card menu.
   */
  int TAPPED_SEND_FEEDBACK = 2;
  /**
   * Discover feed header menu 'Learn More' tapped.
   */
  int TAPPED_LEARN_MORE = 3;
  /**
   * User Tapped Hide Story in the back of card menu.
   */
  int TAPPED_HIDE_STORY = 4;
  /**
   * User Tapped  Not Interested In X in the back of card menu.
   */
  int TAPPED_NOT_INTERESTED_IN = 5;
  /**
   * Discover feed header menu 'Manage Interests' tapped.
   */
  int TAPPED_MANAGE_INTERESTS = 6;
  int TAPPED_DOWNLOAD = 7;
  /**
   * User opened the article in a new tab from the back of card menu.
   */
  int TAPPED_OPEN_IN_NEW_TAB = 8;
  /**
   * User opened the back of card menu.
   */
  int OPENED_CONTEXT_MENU = 9;
  /**
   * User action not reported here. See Suggestions.SurfaceVisible.
   */
  int OPENED_FEED_SURFACE = 10;
  /**
   * User opened the article in an incognito tab from the back of card menu.
   */
  int TAPPED_OPEN_IN_NEW_INCOGNITO_TAB = 11;
  /**
   * Ephemeral change, likely due to hide story or not interested in.
   */
  int EPHEMERAL_CHANGE = 12;
  /**
   * Ephemeral change undone, likely due to pressing 'undo' on the snackbar.
   */
  int EPHEMERAL_CHANGE_REJECTED = 13;
  /**
   * Discover feed visibility toggled from header menu.
   */
  int TAPPED_TURN_ON = 14;
  int TAPPED_TURN_OFF = 15;
  /**
   * Discover feed header menu 'Manage Activity' tapped.
   */
  int TAPPED_MANAGE_ACTIVITY = 16;
  /**
   * User added article to 'Read Later' list. iOS only.
   */
  int ADDED_TO_READ_LATER = 17;
  /**
   * User closed the back of card menu.
   */
  int CLOSED_CONTEXT_MENU = 18;
  /**
   * Ephemeral change committed, likely due to dismissing an 'undo' snackbar.
   */
  int EPHEMERAL_CHANGE_COMMITED = 19;
  /**
   * User opened a Dialog. e.g. Report content Dialog. User action not reported here. iOS only.
   */
  int OPENED_DIALOG = 20;
  /**
   * User closed a Dialog. e.g. Report content Dialog. iOS only.
   */
  int CLOSED_DIALOG = 21;
  /**
   * User action caused a snackbar to be shown. User action not reported here. iOS only.
   */
  int SHOW_SNACKBAR = 22;
  /**
   * User opened back of card menu in the native action sheet. iOS only.
   */
  int OPENED_NATIVE_ACTION_SHEET = 23;
  /**
   * User opened back of card menu in the native context menu. iOS only.
   */
  int OPENED_NATIVE_CONTEXT_MENU = 24;
  /**
   * User closed back of card menu in the native context menu. iOS only.
   */
  int CLOSED_NATIVE_CONTEXT_MENU = 25;
  /**
   * User opened back of card menu in the native pull-down menu. iOS only.
   */
  int OPENED_NATIVE_PULLDOWN_MENU = 26;
  /**
   * User closed back of card menu in the native pull-down menu. iOS only.
   */
  int CLOSED_NATIVE_PULLDOWN_MENU = 27;
  /**
   * User tapped feed header menu item 'Manage reactions'.
   */
  int TAPPED_MANAGE_REACTIONS = 28;
  /**
   * User tapped on share.
   */
  int SHARE = 29;
  /**
   * Tapped the 'Following' option inside the Feed's 'Manage' interstitial.
   */
  int TAPPED_MANAGE_FOLLOWING = 30;
  /**
   * User tapped to follow a web feed on the management surface.
   */
  int TAPPED_FOLLOW_ON_MANAGEMENT_SURFACE = 31;
  /**
   * User tapped to unfollow a web feed on the management surface.
   */
  int TAPPED_UNFOLLOW_ON_MANAGEMENT_SURFACE = 32;
  /**
   * User tapped to follow using the follow accelerator.
   */
  int TAPPED_FOLLOW_ON_FOLLOW_ACCELERATOR = 33;
  /**
   * User tapped to follow using the snackbar 'try again' option.
   */
  int TAPPED_FOLLOW_TRY_AGAIN_ON_SNACKBAR = 34;
  /**
   * User tapped to refollow using the snackbar, after successfully unfollowing.
   */
  int TAPPED_REFOLLOW_AFTER_UNFOLLOW_ON_SNACKBAR = 35;
  /**
   * User tapped to unfollow using the snackbar 'try again' option.
   */
  int TAPPED_UNFOLLOW_TRY_AGAIN_ON_SNACKBAR = 36;
  /**
   * After following an active web feed, the user tapped to go to feed using the post-follow help
   * dialog.
   */
  int TAPPED_GO_TO_FEED_POST_FOLLOW_ACTIVE_HELP = 37;
  /**
   * After following an active web feed, the user tapped to dismiss the post-follow help dialog.
   */
  int TAPPED_DISMISS_POST_FOLLOW_ACTIVE_HELP = 38;
  /**
   * After long-pressing on the feed and seeing the preview, the user tapped on the preview.
   */
  int TAPPED_DISCOVER_FEED_PREVIEW = 39;
  /**
   * User tapped "Settings" link to open feed autoplay settings.
   */
  int OPENED_AUTOPLAY_SETTINGS = 40;
  /**
   * User tapped "Add to Reading List" in the context menu.
   */
  int TAPPED_ADD_TO_READING_LIST = 41;
  /**
   * User tapped "Manage" icon to open the manage intestitial.
   */
  int TAPPED_MANAGE = 42;
  /**
   * User tapped "Hidden" in the manage intestitial.
   */
  int TAPPED_MANAGE_HIDDEN = 43;
  /**
   * User tapped the "Follow" button on the main menu. (Android) User tapped the "Follow" option on
   * the context menu. (IOS)
   */
  int TAPPED_FOLLOW_BUTTON = 44;
  /**
   * User tapped on the Discover feed from the feed header.
   */
  int DISCOVER_FEED_SELECTED = 45;
  /**
   * User tapped on the Following feed from the feed header.
   */
  int FOLLOWING_FEED_SELECTED = 46;
  /**
   * User tapped the "Unfollow" option on the context menu.
   */
  int TAPPED_UNFOLLOW_BUTTON = 47;
  /**
   * User action caused a follow succeed snackbar to be shown. User action not reported here. iOS
   * only.
   */
  int SHOW_FOLLOW_SUCCEED_SNACKBAR = 48;
  /**
   * User action caused a follow failed snackbar to be shown. User action not reported here. iOS
   * only.
   */
  int SHOW_FOLLOW_FAILED_SNACKBAR = 49;
  /**
   * User action caused a unfollow succeed snackbar to be shown. User action not reported here. iOS
   * only.
   */
  int SHOW_UNFOLLOW_SUCCEED_SNACKBAR = 50;
  /**
   * User action caused a unfollow failed snackbar to be shown. User action not reported here. iOS
   * only.
   */
  int SHOW_UNFOLLOW_FAILED_SNACKBAR = 51;
  /**
   * User tapped to go to feed using the snackbar 'go to feed' option.
   */
  int TAPPED_GO_TO_FEED_ON_SNACKBAR = 52;
  /**
   * User tapped the Crow button in the context menu.
   */
  int TAPPED_CROW_BUTTON = 53;
  /**
   * User action caused a first follow sheet to be shown. User action not reported here. iOS only.
   */
  int FIRST_FOLLOW_SHEET_SHOWN = 54;
  /**
   * User tapped the "Go To Feed" button on the first follow sheet. (IOS)
   */
  int FIRST_FOLLOW_SHEET_TAPPED_GO_TO_FEED = 55;
  /**
   * User tapped the "Got It" button on the first follow sheet. (IOS)
   */
  int FIRST_FOLLOW_SHEET_TAPPED_GOT_IT = 56;
  /**
   * Page load caused a Follow Recommendation IPH to be shown. User action not reported here. iOS
   * only.
   */
  int FOLLOW_RECOMMENDATION_IPH_SHOWN = 57;
  /**
   * User opened the article in a new tab in group from the back of card menu.
   */
  int TAPPED_OPEN_IN_NEW_TAB_IN_GROUP = 58;
  int MAX_VALUE = TAPPED_OPEN_IN_NEW_TAB_IN_GROUP;
}
