// RestrictedCookieManager.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/restricted_cookie_manager.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;


public interface RestrictedCookieManager extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends RestrictedCookieManager, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<RestrictedCookieManager, RestrictedCookieManager.Proxy> MANAGER = RestrictedCookieManager_Internal.MANAGER;

    void getAllForUrl(
org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, CookieManagerGetOptions options, boolean partitionedCookiesRuntimeFeatureEnabled, 
GetAllForUrl_Response callback);

    interface GetAllForUrl_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<CookieWithAccessResult[]> { }


    void setCanonicalCookie(
CanonicalCookie cookie, org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, CookieInclusionStatus status, 
SetCanonicalCookie_Response callback);

    interface SetCanonicalCookie_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


    void addChangeListener(
org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, CookieChangeListener listener, 
AddChangeListener_Response callback);

    interface AddChangeListener_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


    void setCookieFromString(
org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, String cookie, boolean partitionedCookiesRuntimeFeatureEnabled, 
SetCookieFromString_Response callback);

    interface SetCookieFromString_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<Boolean, Boolean> { }


    void getCookiesString(
org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, boolean partitionedCookiesRuntimeFeatureEnabled, 
GetCookiesString_Response callback);

    interface GetCookiesString_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<String> { }


    void cookiesEnabledFor(
org.chromium.url.mojom.Url url, SiteForCookies siteForCookies, org.chromium.url.internal.mojom.Origin topFrameOrigin, 
CookiesEnabledFor_Response callback);

    interface CookiesEnabledFor_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


    void convertPartitionedCookiesToUnpartitioned(
org.chromium.url.mojom.Url url);


}
