// DevicePostureProvider.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/device/public/mojom/device_posture_provider.mojom
//

package org.chromium.device.mojom;

import androidx.annotation.IntDef;


public interface DevicePostureProvider extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends DevicePostureProvider, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<DevicePostureProvider, DevicePostureProvider.Proxy> MANAGER = DevicePostureProvider_Internal.MANAGER;

    void addListenerAndGetCurrentPosture(
DevicePostureProviderClient client, 
AddListenerAndGetCurrentPosture_Response callback);

    interface AddListenerAndGetCurrentPosture_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }


}
