
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/android/survey/http_client_type.h

package org.chromium.chrome.browser.survey;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    HttpClientType.SURVEY, HttpClientType.NOTIFICATION
})
@Retention(RetentionPolicy.SOURCE)
public @interface HttpClientType {
  int SURVEY = 0;
  int NOTIFICATION = 1;
}
