
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/feed/core/v2/public/types.h

package org.chromium.chrome.browser.feed;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    OpenActionType.DEFAULT, OpenActionType.NEW_TAB, OpenActionType.NEW_TAB_IN_GROUP
})
@Retention(RetentionPolicy.SOURCE)
public @interface OpenActionType {
  /**
   * The default open action.
   */
  int DEFAULT = 0;
  /**
   * "Open in new tab" action.
   */
  int NEW_TAB = 1;
  /**
   * "Open in new tab in group" action.
   */
  int NEW_TAB_IN_GROUP = 2;
}
