
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/messages/android/message_enums.h

package org.chromium.components.messages;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PrimaryWidgetAppearance.BUTTON_IF_TEXT_IS_SET, PrimaryWidgetAppearance.PROGRESS_SPINNER
})
@Retention(RetentionPolicy.SOURCE)
public @interface PrimaryWidgetAppearance {
  /**
   * Default value. Show the primary action button if non-empty text has been set for the primary
   * action button, otherwise no primary widget is shown.
   */
  int BUTTON_IF_TEXT_IS_SET = 0;
  /**
   * Show a spinning progress indicator that isn't clickable.
   */
  int PROGRESS_SPINNER = 1;
}
