
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/omnibox/browser/actions/omnibox_action_concepts.h

package org.chromium.chrome.browser.omnibox.action;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    OmniboxActionType.FIRST, OmniboxActionType.HISTORY_CLUSTERS, OmniboxActionType.LAST
})
@Retention(RetentionPolicy.SOURCE)
public @interface OmniboxActionType {
  int FIRST = 10000;
  int HISTORY_CLUSTERS = 10001;
  /**
   * Last value, used to track the upper bound. This intentionally does not have an assigned value
   * to ensure that it's always 1 greater than the last assigned value.
   */
  int LAST = 10002;
}
