
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/payments/core/pre_purchase_query.h

package org.chromium.components.payments;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PrePurchaseQuery.OTHER_TYPE_OF_QUERY, PrePurchaseQuery.SERVICE_WORKER_EVENT,
    PrePurchaseQuery.ANDROID_INTENT, PrePurchaseQuery.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface PrePurchaseQuery {
  int OTHER_TYPE_OF_QUERY = 0;
  int SERVICE_WORKER_EVENT = 1;
  int ANDROID_INTENT = 2;
  int MAX_VALUE = ANDROID_INTENT;
}
