// GpuAcceleratedVideoDecoderProvider.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/gpu_accelerated_video_decoder.mojom
//

package org.chromium.media.mojom;

import androidx.annotation.IntDef;


public interface GpuAcceleratedVideoDecoderProvider extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends GpuAcceleratedVideoDecoderProvider, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<GpuAcceleratedVideoDecoderProvider, GpuAcceleratedVideoDecoderProvider.Proxy> MANAGER = GpuAcceleratedVideoDecoderProvider_Internal.MANAGER;

    void createAcceleratedVideoDecoder(
VideoDecodeAcceleratorConfig config, org.chromium.mojo.bindings.AssociatedInterfaceRequestNotSupported receiver, org.chromium.mojo.bindings.AssociatedInterfaceNotSupported client, 
CreateAcceleratedVideoDecoder_Response callback);

    interface CreateAcceleratedVideoDecoder_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


}
