// PictureReadyParams.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/gpu_accelerated_video_decoder.mojom
//

package org.chromium.media.mojom;

import androidx.annotation.IntDef;


public final class PictureReadyParams extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 40;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(40, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public int pictureBufferId;
    public int bitstreamBufferId;
    public org.chromium.gfx.mojom.Rect visibleRect;
    public org.chromium.gfx.mojom.ColorSpace colorSpace;
    public boolean allowOverlay;
    public boolean readLockFencesEnabled;
    public boolean sizeChanged;
    public boolean surfaceTexture;
    public boolean wantsPromotionHint;

    private PictureReadyParams(int version) {
        super(STRUCT_SIZE, version);
    }

    public PictureReadyParams() {
        this(0);
    }

    public static PictureReadyParams deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static PictureReadyParams deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static PictureReadyParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        PictureReadyParams result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new PictureReadyParams(elementsOrVersion);
                {
                    
                result.pictureBufferId = decoder0.readInt(8);
                }
                {
                    
                result.bitstreamBufferId = decoder0.readInt(12);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(16, false);
                result.visibleRect = org.chromium.gfx.mojom.Rect.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(24, false);
                result.colorSpace = org.chromium.gfx.mojom.ColorSpace.decode(decoder1);
                }
                {
                    
                result.allowOverlay = decoder0.readBoolean(32, 0);
                }
                {
                    
                result.readLockFencesEnabled = decoder0.readBoolean(32, 1);
                }
                {
                    
                result.sizeChanged = decoder0.readBoolean(32, 2);
                }
                {
                    
                result.surfaceTexture = decoder0.readBoolean(32, 3);
                }
                {
                    
                result.wantsPromotionHint = decoder0.readBoolean(32, 4);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.pictureBufferId, 8);
        
        encoder0.encode(this.bitstreamBufferId, 12);
        
        encoder0.encode(this.visibleRect, 16, false);
        
        encoder0.encode(this.colorSpace, 24, false);
        
        encoder0.encode(this.allowOverlay, 32, 0);
        
        encoder0.encode(this.readLockFencesEnabled, 32, 1);
        
        encoder0.encode(this.sizeChanged, 32, 2);
        
        encoder0.encode(this.surfaceTexture, 32, 3);
        
        encoder0.encode(this.wantsPromotionHint, 32, 4);
    }
}