// SvcScalabilityMode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/media_types.mojom
//

package org.chromium.media.mojom;

import androidx.annotation.IntDef;

public final class SvcScalabilityMode {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        SvcScalabilityMode.UNSUPPORTED_MODE,
        SvcScalabilityMode.L1T2,
        SvcScalabilityMode.L1T3,
        SvcScalabilityMode.L2T2_KEY,
        SvcScalabilityMode.L2T3_KEY,
        SvcScalabilityMode.L3T2_KEY,
        SvcScalabilityMode.L3T3_KEY})
    public @interface EnumType {}

    public static final int UNSUPPORTED_MODE = 0;
    public static final int L1T2 = 1;
    public static final int L1T3 = 2;
    public static final int L2T2_KEY = 3;
    public static final int L2T3_KEY = 4;
    public static final int L3T2_KEY = 5;
    public static final int L3T3_KEY = 6;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 6;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 6;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private SvcScalabilityMode() {}
}