
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/password_manager/core/browser/password_manager_setting.h

package org.chromium.chrome.browser.password_manager;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PasswordManagerSetting.OFFER_TO_SAVE_PASSWORDS, PasswordManagerSetting.AUTO_SIGN_IN,
    PasswordManagerSetting.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface PasswordManagerSetting {
  /**
   * Setting controlling whether the password manager offers password saving.
   */
  int OFFER_TO_SAVE_PASSWORDS = 0;
  /**
   * Setting controlling whether the password manager can use the automatically sign in users based
   * on their saved passwords on sites which support this.
   */
  int AUTO_SIGN_IN = 1;
  int MAX_VALUE = AUTO_SIGN_IN;
}
