
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/password_manager/core/browser/password_manager_metrics_util.h

package org.chromium.chrome.browser.password_manager;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ReauthResult.SUCCESS, ReauthResult.FAILURE, ReauthResult.SKIPPED, ReauthResult.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface ReauthResult {
  int SUCCESS = 0;
  int FAILURE = 1;
  int SKIPPED = 2;
  int MAX_VALUE = SKIPPED;
}
