// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/autofill_wallet_usage_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * Protobuf type {@code sync_pb.AutofillWalletUsageSpecifics}
 */
public  final class AutofillWalletUsageSpecifics extends
    com.google.protobuf.GeneratedMessageLite<
        AutofillWalletUsageSpecifics, AutofillWalletUsageSpecifics.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.AutofillWalletUsageSpecifics)
    AutofillWalletUsageSpecificsOrBuilder {
  private AutofillWalletUsageSpecifics() {
    guid_ = "";
    retrievalTimeUnixEpochMicros_ = emptyLongList();
  }
  public interface VirtualCardUsageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     * @return Whether the instrumentId field is set.
     */
    boolean hasInstrumentId();
    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     * @return The instrumentId.
     */
    long getInstrumentId();

    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return Whether the virtualCardLastFour field is set.
     */
    boolean hasVirtualCardLastFour();
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return The virtualCardLastFour.
     */
    java.lang.String getVirtualCardLastFour();
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return The bytes for virtualCardLastFour.
     */
    com.google.protobuf.ByteString
        getVirtualCardLastFourBytes();

    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return Whether the merchantUrl field is set.
     */
    boolean hasMerchantUrl();
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return The merchantUrl.
     */
    java.lang.String getMerchantUrl();
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return The bytes for merchantUrl.
     */
    com.google.protobuf.ByteString
        getMerchantUrlBytes();

    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return Whether the merchantAppPackage field is set.
     */
    boolean hasMerchantAppPackage();
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return The merchantAppPackage.
     */
    java.lang.String getMerchantAppPackage();
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return The bytes for merchantAppPackage.
     */
    com.google.protobuf.ByteString
        getMerchantAppPackageBytes();
  }
  /**
   * Protobuf type {@code sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData}
   */
  public  static final class VirtualCardUsageData extends
      com.google.protobuf.GeneratedMessageLite<
          VirtualCardUsageData, VirtualCardUsageData.Builder> implements
      // @@protoc_insertion_point(message_implements:sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData)
      VirtualCardUsageDataOrBuilder {
    private VirtualCardUsageData() {
      virtualCardLastFour_ = "";
      merchantUrl_ = "";
      merchantAppPackage_ = "";
    }
    private int bitField0_;
    public static final int INSTRUMENT_ID_FIELD_NUMBER = 1;
    private long instrumentId_;
    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     * @return Whether the instrumentId field is set.
     */
    @java.lang.Override
    public boolean hasInstrumentId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     * @return The instrumentId.
     */
    @java.lang.Override
    public long getInstrumentId() {
      return instrumentId_;
    }
    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     * @param value The instrumentId to set.
     */
    private void setInstrumentId(long value) {
      bitField0_ |= 0x00000001;
      instrumentId_ = value;
    }
    /**
     * <pre>
     * The instrument id of the actual card that the virtual card is related to.
     * </pre>
     *
     * <code>optional int64 instrument_id = 1;</code>
     */
    private void clearInstrumentId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      instrumentId_ = 0L;
    }

    public static final int VIRTUAL_CARD_LAST_FOUR_FIELD_NUMBER = 2;
    private java.lang.String virtualCardLastFour_;
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return Whether the virtualCardLastFour field is set.
     */
    @java.lang.Override
    public boolean hasVirtualCardLastFour() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return The virtualCardLastFour.
     */
    @java.lang.Override
    public java.lang.String getVirtualCardLastFour() {
      return virtualCardLastFour_;
    }
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @return The bytes for virtualCardLastFour.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVirtualCardLastFourBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(virtualCardLastFour_);
    }
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @param value The virtualCardLastFour to set.
     */
    private void setVirtualCardLastFour(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      virtualCardLastFour_ = value;
    }
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     */
    private void clearVirtualCardLastFour() {
      bitField0_ = (bitField0_ & ~0x00000002);
      virtualCardLastFour_ = getDefaultInstance().getVirtualCardLastFour();
    }
    /**
     * <pre>
     * The last four of the virtual card number. This is tied to the usage
     * data because the virtual card number may vary depending on merchants.
     * </pre>
     *
     * <code>optional string virtual_card_last_four = 2;</code>
     * @param value The bytes for virtualCardLastFour to set.
     */
    private void setVirtualCardLastFourBytes(
        com.google.protobuf.ByteString value) {
      virtualCardLastFour_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int MERCHANT_URL_FIELD_NUMBER = 3;
    private java.lang.String merchantUrl_;
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return Whether the merchantUrl field is set.
     */
    @java.lang.Override
    public boolean hasMerchantUrl() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return The merchantUrl.
     */
    @java.lang.Override
    public java.lang.String getMerchantUrl() {
      return merchantUrl_;
    }
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @return The bytes for merchantUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMerchantUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(merchantUrl_);
    }
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @param value The merchantUrl to set.
     */
    private void setMerchantUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      merchantUrl_ = value;
    }
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     */
    private void clearMerchantUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      merchantUrl_ = getDefaultInstance().getMerchantUrl();
    }
    /**
     * <pre>
     * The url of the merchant where the virtual card is used.
     * </pre>
     *
     * <code>optional string merchant_url = 3;</code>
     * @param value The bytes for merchantUrl to set.
     */
    private void setMerchantUrlBytes(
        com.google.protobuf.ByteString value) {
      merchantUrl_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int MERCHANT_APP_PACKAGE_FIELD_NUMBER = 4;
    private java.lang.String merchantAppPackage_;
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return Whether the merchantAppPackage field is set.
     */
    @java.lang.Override
    public boolean hasMerchantAppPackage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return The merchantAppPackage.
     */
    @java.lang.Override
    public java.lang.String getMerchantAppPackage() {
      return merchantAppPackage_;
    }
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @return The bytes for merchantAppPackage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMerchantAppPackageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(merchantAppPackage_);
    }
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @param value The merchantAppPackage to set.
     */
    private void setMerchantAppPackage(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000008;
      merchantAppPackage_ = value;
    }
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     */
    private void clearMerchantAppPackage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      merchantAppPackage_ = getDefaultInstance().getMerchantAppPackage();
    }
    /**
     * <pre>
     * The merchant the usage data is related to on the Android platform.
     * </pre>
     *
     * <code>optional string merchant_app_package = 4;</code>
     * @param value The bytes for merchantAppPackage to set.
     */
    private void setMerchantAppPackageBytes(
        com.google.protobuf.ByteString value) {
      merchantAppPackage_ = value.toStringUtf8();
      bitField0_ |= 0x00000008;
    }

    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData, Builder> implements
        // @@protoc_insertion_point(builder_implements:sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData)
        org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageDataOrBuilder {
      // Construct using org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The instrument id of the actual card that the virtual card is related to.
       * </pre>
       *
       * <code>optional int64 instrument_id = 1;</code>
       * @return Whether the instrumentId field is set.
       */
      @java.lang.Override
      public boolean hasInstrumentId() {
        return instance.hasInstrumentId();
      }
      /**
       * <pre>
       * The instrument id of the actual card that the virtual card is related to.
       * </pre>
       *
       * <code>optional int64 instrument_id = 1;</code>
       * @return The instrumentId.
       */
      @java.lang.Override
      public long getInstrumentId() {
        return instance.getInstrumentId();
      }
      /**
       * <pre>
       * The instrument id of the actual card that the virtual card is related to.
       * </pre>
       *
       * <code>optional int64 instrument_id = 1;</code>
       * @param value The instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentId(long value) {
        copyOnWrite();
        instance.setInstrumentId(value);
        return this;
      }
      /**
       * <pre>
       * The instrument id of the actual card that the virtual card is related to.
       * </pre>
       *
       * <code>optional int64 instrument_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstrumentId() {
        copyOnWrite();
        instance.clearInstrumentId();
        return this;
      }

      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @return Whether the virtualCardLastFour field is set.
       */
      @java.lang.Override
      public boolean hasVirtualCardLastFour() {
        return instance.hasVirtualCardLastFour();
      }
      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @return The virtualCardLastFour.
       */
      @java.lang.Override
      public java.lang.String getVirtualCardLastFour() {
        return instance.getVirtualCardLastFour();
      }
      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @return The bytes for virtualCardLastFour.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVirtualCardLastFourBytes() {
        return instance.getVirtualCardLastFourBytes();
      }
      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @param value The virtualCardLastFour to set.
       * @return This builder for chaining.
       */
      public Builder setVirtualCardLastFour(
          java.lang.String value) {
        copyOnWrite();
        instance.setVirtualCardLastFour(value);
        return this;
      }
      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVirtualCardLastFour() {
        copyOnWrite();
        instance.clearVirtualCardLastFour();
        return this;
      }
      /**
       * <pre>
       * The last four of the virtual card number. This is tied to the usage
       * data because the virtual card number may vary depending on merchants.
       * </pre>
       *
       * <code>optional string virtual_card_last_four = 2;</code>
       * @param value The bytes for virtualCardLastFour to set.
       * @return This builder for chaining.
       */
      public Builder setVirtualCardLastFourBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVirtualCardLastFourBytes(value);
        return this;
      }

      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @return Whether the merchantUrl field is set.
       */
      @java.lang.Override
      public boolean hasMerchantUrl() {
        return instance.hasMerchantUrl();
      }
      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @return The merchantUrl.
       */
      @java.lang.Override
      public java.lang.String getMerchantUrl() {
        return instance.getMerchantUrl();
      }
      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @return The bytes for merchantUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMerchantUrlBytes() {
        return instance.getMerchantUrlBytes();
      }
      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @param value The merchantUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setMerchantUrl(value);
        return this;
      }
      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantUrl() {
        copyOnWrite();
        instance.clearMerchantUrl();
        return this;
      }
      /**
       * <pre>
       * The url of the merchant where the virtual card is used.
       * </pre>
       *
       * <code>optional string merchant_url = 3;</code>
       * @param value The bytes for merchantUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMerchantUrlBytes(value);
        return this;
      }

      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @return Whether the merchantAppPackage field is set.
       */
      @java.lang.Override
      public boolean hasMerchantAppPackage() {
        return instance.hasMerchantAppPackage();
      }
      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @return The merchantAppPackage.
       */
      @java.lang.Override
      public java.lang.String getMerchantAppPackage() {
        return instance.getMerchantAppPackage();
      }
      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @return The bytes for merchantAppPackage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMerchantAppPackageBytes() {
        return instance.getMerchantAppPackageBytes();
      }
      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @param value The merchantAppPackage to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantAppPackage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMerchantAppPackage(value);
        return this;
      }
      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantAppPackage() {
        copyOnWrite();
        instance.clearMerchantAppPackage();
        return this;
      }
      /**
       * <pre>
       * The merchant the usage data is related to on the Android platform.
       * </pre>
       *
       * <code>optional string merchant_app_package = 4;</code>
       * @param value The bytes for merchantAppPackage to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantAppPackageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMerchantAppPackageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "instrumentId_",
              "virtualCardLastFour_",
              "merchantUrl_",
              "merchantAppPackage_",
            };
            java.lang.String info =
                "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u1002\u0000\u0002" +
                "\u1008\u0001\u0003\u1008\u0002\u0004\u1008\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData)
    private static final org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData DEFAULT_INSTANCE;
    static {
      VirtualCardUsageData defaultInstance = new VirtualCardUsageData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        VirtualCardUsageData.class, defaultInstance);
    }

    public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<VirtualCardUsageData> PARSER;

    public static com.google.protobuf.Parser<VirtualCardUsageData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  private int usageDataTypeCase_ = 0;
  private java.lang.Object usageDataType_;
  public enum UsageDataTypeCase {
    VIRTUAL_CARD_USAGE_DATA(2),
    USAGEDATATYPE_NOT_SET(0);
    private final int value;
    private UsageDataTypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UsageDataTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static UsageDataTypeCase forNumber(int value) {
      switch (value) {
        case 2: return VIRTUAL_CARD_USAGE_DATA;
        case 0: return USAGEDATATYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public UsageDataTypeCase
  getUsageDataTypeCase() {
    return UsageDataTypeCase.forNumber(
        usageDataTypeCase_);
  }

  private void clearUsageDataType() {
    usageDataTypeCase_ = 0;
    usageDataType_ = null;
  }

  public static final int GUID_FIELD_NUMBER = 1;
  private java.lang.String guid_;
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   * @return Whether the guid field is set.
   */
  @java.lang.Override
  public boolean hasGuid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   * @return The guid.
   */
  @java.lang.Override
  public java.lang.String getGuid() {
    return guid_;
  }
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   * @return The bytes for guid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(guid_);
  }
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   * @param value The guid to set.
   */
  private void setGuid(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000001;
    guid_ = value;
  }
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  private void clearGuid() {
    bitField0_ = (bitField0_ & ~0x00000001);
    guid_ = getDefaultInstance().getGuid();
  }
  /**
   * <pre>
   * A unique ID identifying this item. Used as the client tag.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   * @param value The bytes for guid to set.
   */
  private void setGuidBytes(
      com.google.protobuf.ByteString value) {
    guid_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int VIRTUAL_CARD_USAGE_DATA_FIELD_NUMBER = 2;
  /**
   * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
   */
  @java.lang.Override
  public boolean hasVirtualCardUsageData() {
    return usageDataTypeCase_ == 2;
  }
  /**
   * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
   */
  @java.lang.Override
  public org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData getVirtualCardUsageData() {
    if (usageDataTypeCase_ == 2) {
       return (org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData) usageDataType_;
    }
    return org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.getDefaultInstance();
  }
  /**
   * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
   */
  private void setVirtualCardUsageData(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData value) {
    value.getClass();
  usageDataType_ = value;
    usageDataTypeCase_ = 2;
  }
  /**
   * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
   */
  private void mergeVirtualCardUsageData(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData value) {
    value.getClass();
  if (usageDataTypeCase_ == 2 &&
        usageDataType_ != org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.getDefaultInstance()) {
      usageDataType_ = org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.newBuilder((org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData) usageDataType_)
          .mergeFrom(value).buildPartial();
    } else {
      usageDataType_ = value;
    }
    usageDataTypeCase_ = 2;
  }
  /**
   * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
   */
  private void clearVirtualCardUsageData() {
    if (usageDataTypeCase_ == 2) {
      usageDataTypeCase_ = 0;
      usageDataType_ = null;
    }
  }

  public static final int RETRIEVAL_TIME_UNIX_EPOCH_MICROS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList retrievalTimeUnixEpochMicros_;
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @return A list containing the retrievalTimeUnixEpochMicros.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getRetrievalTimeUnixEpochMicrosList() {
    return retrievalTimeUnixEpochMicros_;
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @return The count of retrievalTimeUnixEpochMicros.
   */
  @java.lang.Override
  public int getRetrievalTimeUnixEpochMicrosCount() {
    return retrievalTimeUnixEpochMicros_.size();
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The retrievalTimeUnixEpochMicros at the given index.
   */
  @java.lang.Override
  public long getRetrievalTimeUnixEpochMicros(int index) {
    return retrievalTimeUnixEpochMicros_.getLong(index);
  }
  private int retrievalTimeUnixEpochMicrosMemoizedSerializedSize = -1;
  private void ensureRetrievalTimeUnixEpochMicrosIsMutable() {
    com.google.protobuf.Internal.LongList tmp = retrievalTimeUnixEpochMicros_;
    if (!tmp.isModifiable()) {
      retrievalTimeUnixEpochMicros_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @param index The index to set the value at.
   * @param value The retrievalTimeUnixEpochMicros to set.
   */
  private void setRetrievalTimeUnixEpochMicros(
      int index, long value) {
    ensureRetrievalTimeUnixEpochMicrosIsMutable();
    retrievalTimeUnixEpochMicros_.setLong(index, value);
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @param value The retrievalTimeUnixEpochMicros to add.
   */
  private void addRetrievalTimeUnixEpochMicros(long value) {
    ensureRetrievalTimeUnixEpochMicrosIsMutable();
    retrievalTimeUnixEpochMicros_.addLong(value);
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   * @param values The retrievalTimeUnixEpochMicros to add.
   */
  private void addAllRetrievalTimeUnixEpochMicros(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureRetrievalTimeUnixEpochMicrosIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, retrievalTimeUnixEpochMicros_);
  }
  /**
   * <pre>
   * A list of timestamps that correspond to the latest retrieval requests of a
   * specific Autofill wallet data model. These timestamps are collected when a
   * user selects an option in a Autofill suggestion dropdown and the client
   * records the time.
   * </pre>
   *
   * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
   */
  private void clearRetrievalTimeUnixEpochMicros() {
    retrievalTimeUnixEpochMicros_ = emptyLongList();
  }

  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sync_pb.AutofillWalletUsageSpecifics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.AutofillWalletUsageSpecifics)
      org.chromium.components.sync.protocol.AutofillWalletUsageSpecificsOrBuilder {
    // Construct using org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public UsageDataTypeCase
        getUsageDataTypeCase() {
      return instance.getUsageDataTypeCase();
    }

    public Builder clearUsageDataType() {
      copyOnWrite();
      instance.clearUsageDataType();
      return this;
    }


    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @return Whether the guid field is set.
     */
    @java.lang.Override
    public boolean hasGuid() {
      return instance.hasGuid();
    }
    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @return The guid.
     */
    @java.lang.Override
    public java.lang.String getGuid() {
      return instance.getGuid();
    }
    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @return The bytes for guid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGuidBytes() {
      return instance.getGuidBytes();
    }
    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @param value The guid to set.
     * @return This builder for chaining.
     */
    public Builder setGuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setGuid(value);
      return this;
    }
    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGuid() {
      copyOnWrite();
      instance.clearGuid();
      return this;
    }
    /**
     * <pre>
     * A unique ID identifying this item. Used as the client tag.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     * @param value The bytes for guid to set.
     * @return This builder for chaining.
     */
    public Builder setGuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGuidBytes(value);
      return this;
    }

    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    @java.lang.Override
    public boolean hasVirtualCardUsageData() {
      return instance.hasVirtualCardUsageData();
    }
    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    @java.lang.Override
    public org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData getVirtualCardUsageData() {
      return instance.getVirtualCardUsageData();
    }
    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    public Builder setVirtualCardUsageData(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData value) {
      copyOnWrite();
      instance.setVirtualCardUsageData(value);
      return this;
    }
    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    public Builder setVirtualCardUsageData(
        org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.Builder builderForValue) {
      copyOnWrite();
      instance.setVirtualCardUsageData(builderForValue.build());
      return this;
    }
    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    public Builder mergeVirtualCardUsageData(org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData value) {
      copyOnWrite();
      instance.mergeVirtualCardUsageData(value);
      return this;
    }
    /**
     * <code>.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageData virtual_card_usage_data = 2;</code>
     */
    public Builder clearVirtualCardUsageData() {
      copyOnWrite();
      instance.clearVirtualCardUsageData();
      return this;
    }

    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @return A list containing the retrievalTimeUnixEpochMicros.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getRetrievalTimeUnixEpochMicrosList() {
      return java.util.Collections.unmodifiableList(
          instance.getRetrievalTimeUnixEpochMicrosList());
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @return The count of retrievalTimeUnixEpochMicros.
     */
    @java.lang.Override
    public int getRetrievalTimeUnixEpochMicrosCount() {
      return instance.getRetrievalTimeUnixEpochMicrosCount();
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The retrievalTimeUnixEpochMicros at the given index.
     */
    @java.lang.Override
    public long getRetrievalTimeUnixEpochMicros(int index) {
      return instance.getRetrievalTimeUnixEpochMicros(index);
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @param value The retrievalTimeUnixEpochMicros to set.
     * @return This builder for chaining.
     */
    public Builder setRetrievalTimeUnixEpochMicros(
        int index, long value) {
      copyOnWrite();
      instance.setRetrievalTimeUnixEpochMicros(index, value);
      return this;
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @param value The retrievalTimeUnixEpochMicros to add.
     * @return This builder for chaining.
     */
    public Builder addRetrievalTimeUnixEpochMicros(long value) {
      copyOnWrite();
      instance.addRetrievalTimeUnixEpochMicros(value);
      return this;
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @param values The retrievalTimeUnixEpochMicros to add.
     * @return This builder for chaining.
     */
    public Builder addAllRetrievalTimeUnixEpochMicros(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllRetrievalTimeUnixEpochMicros(values);
      return this;
    }
    /**
     * <pre>
     * A list of timestamps that correspond to the latest retrieval requests of a
     * specific Autofill wallet data model. These timestamps are collected when a
     * user selects an option in a Autofill suggestion dropdown and the client
     * records the time.
     * </pre>
     *
     * <code>repeated int64 retrieval_time_unix_epoch_micros = 3 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetrievalTimeUnixEpochMicros() {
      copyOnWrite();
      instance.clearRetrievalTimeUnixEpochMicros();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.AutofillWalletUsageSpecifics)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "usageDataType_",
            "usageDataTypeCase_",
            "bitField0_",
            "guid_",
            org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.VirtualCardUsageData.class,
            "retrievalTimeUnixEpochMicros_",
          };
          java.lang.String info =
              "\u0001\u0003\u0001\u0001\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u1008\u0000\u0002" +
              "\u103c\u0000\u0003%";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.AutofillWalletUsageSpecifics)
  private static final org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics DEFAULT_INSTANCE;
  static {
    AutofillWalletUsageSpecifics defaultInstance = new AutofillWalletUsageSpecifics();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AutofillWalletUsageSpecifics.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.AutofillWalletUsageSpecifics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AutofillWalletUsageSpecifics> PARSER;

  public static com.google.protobuf.Parser<AutofillWalletUsageSpecifics> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

