// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/device_info_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * Protobuf type {@code sync_pb.ChromeVersionInfo}
 */
public  final class ChromeVersionInfo extends
    com.google.protobuf.GeneratedMessageLite<
        ChromeVersionInfo, ChromeVersionInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.ChromeVersionInfo)
    ChromeVersionInfoOrBuilder {
  private ChromeVersionInfo() {
    versionNumber_ = "";
  }
  private int bitField0_;
  public static final int VERSION_NUMBER_FIELD_NUMBER = 1;
  private java.lang.String versionNumber_;
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   * @return Whether the versionNumber field is set.
   */
  @java.lang.Override
  public boolean hasVersionNumber() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   * @return The versionNumber.
   */
  @java.lang.Override
  public java.lang.String getVersionNumber() {
    return versionNumber_;
  }
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   * @return The bytes for versionNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionNumberBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(versionNumber_);
  }
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   * @param value The versionNumber to set.
   */
  private void setVersionNumber(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000001;
    versionNumber_ = value;
  }
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   */
  private void clearVersionNumber() {
    bitField0_ = (bitField0_ & ~0x00000001);
    versionNumber_ = getDefaultInstance().getVersionNumber();
  }
  /**
   * <pre>
   * Version number as per https://www.chromium.org/developers/version-numbers.
   * </pre>
   *
   * <code>optional string version_number = 1;</code>
   * @param value The bytes for versionNumber to set.
   */
  private void setVersionNumberBytes(
      com.google.protobuf.ByteString value) {
    versionNumber_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ChromeVersionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.ChromeVersionInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sync_pb.ChromeVersionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.ChromeVersionInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.ChromeVersionInfo)
      org.chromium.components.sync.protocol.ChromeVersionInfoOrBuilder {
    // Construct using org.chromium.components.sync.protocol.ChromeVersionInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @return Whether the versionNumber field is set.
     */
    @java.lang.Override
    public boolean hasVersionNumber() {
      return instance.hasVersionNumber();
    }
    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @return The versionNumber.
     */
    @java.lang.Override
    public java.lang.String getVersionNumber() {
      return instance.getVersionNumber();
    }
    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @return The bytes for versionNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionNumberBytes() {
      return instance.getVersionNumberBytes();
    }
    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @param value The versionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setVersionNumber(
        java.lang.String value) {
      copyOnWrite();
      instance.setVersionNumber(value);
      return this;
    }
    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersionNumber() {
      copyOnWrite();
      instance.clearVersionNumber();
      return this;
    }
    /**
     * <pre>
     * Version number as per https://www.chromium.org/developers/version-numbers.
     * </pre>
     *
     * <code>optional string version_number = 1;</code>
     * @param value The bytes for versionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setVersionNumberBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionNumberBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.ChromeVersionInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.ChromeVersionInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "versionNumber_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1008\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.ChromeVersionInfo> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.ChromeVersionInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.ChromeVersionInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.ChromeVersionInfo)
  private static final org.chromium.components.sync.protocol.ChromeVersionInfo DEFAULT_INSTANCE;
  static {
    ChromeVersionInfo defaultInstance = new ChromeVersionInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChromeVersionInfo.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.ChromeVersionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChromeVersionInfo> PARSER;

  public static com.google.protobuf.Parser<ChromeVersionInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

