// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/device_info_specifics.proto

package org.chromium.components.sync.protocol;

public interface DeviceInfoSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.DeviceInfoSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The cache_guid created to identify a sync client on this device.
   * </pre>
   *
   * <code>optional string cache_guid = 1;</code>
   * @return Whether the cacheGuid field is set.
   */
  boolean hasCacheGuid();
  /**
   * <pre>
   * The cache_guid created to identify a sync client on this device.
   * </pre>
   *
   * <code>optional string cache_guid = 1;</code>
   * @return The cacheGuid.
   */
  java.lang.String getCacheGuid();
  /**
   * <pre>
   * The cache_guid created to identify a sync client on this device.
   * </pre>
   *
   * <code>optional string cache_guid = 1;</code>
   * @return The bytes for cacheGuid.
   */
  com.google.protobuf.ByteString
      getCacheGuidBytes();

  /**
   * <pre>
   * A non-unique but human readable name to describe this client.
   * </pre>
   *
   * <code>optional string client_name = 2;</code>
   * @return Whether the clientName field is set.
   */
  boolean hasClientName();
  /**
   * <pre>
   * A non-unique but human readable name to describe this client.
   * </pre>
   *
   * <code>optional string client_name = 2;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <pre>
   * A non-unique but human readable name to describe this client.
   * </pre>
   *
   * <code>optional string client_name = 2;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <pre>
   * The platform of the device.
   * </pre>
   *
   * <code>optional .sync_pb.SyncEnums.DeviceType device_type = 3;</code>
   * @return Whether the deviceType field is set.
   */
  boolean hasDeviceType();
  /**
   * <pre>
   * The platform of the device.
   * </pre>
   *
   * <code>optional .sync_pb.SyncEnums.DeviceType device_type = 3;</code>
   * @return The deviceType.
   */
  org.chromium.components.sync.protocol.SyncEnums.DeviceType getDeviceType();

  /**
   * <pre>
   * The UserAgent used when contacting the Chrome Sync server.
   * Only present when talking to the HTTP server.
   * </pre>
   *
   * <code>optional string sync_user_agent = 4;</code>
   * @return Whether the syncUserAgent field is set.
   */
  boolean hasSyncUserAgent();
  /**
   * <pre>
   * The UserAgent used when contacting the Chrome Sync server.
   * Only present when talking to the HTTP server.
   * </pre>
   *
   * <code>optional string sync_user_agent = 4;</code>
   * @return The syncUserAgent.
   */
  java.lang.String getSyncUserAgent();
  /**
   * <pre>
   * The UserAgent used when contacting the Chrome Sync server.
   * Only present when talking to the HTTP server.
   * </pre>
   *
   * <code>optional string sync_user_agent = 4;</code>
   * @return The bytes for syncUserAgent.
   */
  com.google.protobuf.ByteString
      getSyncUserAgentBytes();

  /**
   * <pre>
   * The Chrome instance's version.  Updated (if necessary) on every startup.
   * DEPRECATED in M92. Still populated for backward compatibility.
   * </pre>
   *
   * <code>optional string chrome_version = 5 [deprecated = true];</code>
   * @return Whether the chromeVersion field is set.
   */
  @java.lang.Deprecated boolean hasChromeVersion();
  /**
   * <pre>
   * The Chrome instance's version.  Updated (if necessary) on every startup.
   * DEPRECATED in M92. Still populated for backward compatibility.
   * </pre>
   *
   * <code>optional string chrome_version = 5 [deprecated = true];</code>
   * @return The chromeVersion.
   */
  @java.lang.Deprecated java.lang.String getChromeVersion();
  /**
   * <pre>
   * The Chrome instance's version.  Updated (if necessary) on every startup.
   * DEPRECATED in M92. Still populated for backward compatibility.
   * </pre>
   *
   * <code>optional string chrome_version = 5 [deprecated = true];</code>
   * @return The bytes for chromeVersion.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getChromeVersionBytes();

  /**
   * <pre>
   * Last time when pre-sync data on the device was saved. The device can be
   * restored to state back to this time. In millisecond since UNIX epoch.
   * DEPRECATED in M50.
   * </pre>
   *
   * <code>optional int64 deprecated_backup_timestamp = 6 [deprecated = true];</code>
   * @return Whether the deprecatedBackupTimestamp field is set.
   */
  @java.lang.Deprecated boolean hasDeprecatedBackupTimestamp();
  /**
   * <pre>
   * Last time when pre-sync data on the device was saved. The device can be
   * restored to state back to this time. In millisecond since UNIX epoch.
   * DEPRECATED in M50.
   * </pre>
   *
   * <code>optional int64 deprecated_backup_timestamp = 6 [deprecated = true];</code>
   * @return The deprecatedBackupTimestamp.
   */
  @java.lang.Deprecated long getDeprecatedBackupTimestamp();

  /**
   * <pre>
   * Device_id that is stable until user signs out. This device_id is used for
   * annotating login scoped refresh token. Present only for Chrome Clients.
   * </pre>
   *
   * <code>optional string signin_scoped_device_id = 7;</code>
   * @return Whether the signinScopedDeviceId field is set.
   */
  boolean hasSigninScopedDeviceId();
  /**
   * <pre>
   * Device_id that is stable until user signs out. This device_id is used for
   * annotating login scoped refresh token. Present only for Chrome Clients.
   * </pre>
   *
   * <code>optional string signin_scoped_device_id = 7;</code>
   * @return The signinScopedDeviceId.
   */
  java.lang.String getSigninScopedDeviceId();
  /**
   * <pre>
   * Device_id that is stable until user signs out. This device_id is used for
   * annotating login scoped refresh token. Present only for Chrome Clients.
   * </pre>
   *
   * <code>optional string signin_scoped_device_id = 7;</code>
   * @return The bytes for signinScopedDeviceId.
   */
  com.google.protobuf.ByteString
      getSigninScopedDeviceIdBytes();

  /**
   * <pre>
   * This field is updated to be the current time periodically, and is also set
   * to the current time whenever another field changes. By examining the
   * difference between this field and the current time, it should be possible
   * to reason about the inactivity of any device that was syncing at one time.
   * </pre>
   *
   * <code>optional int64 last_updated_timestamp = 8;</code>
   * @return Whether the lastUpdatedTimestamp field is set.
   */
  boolean hasLastUpdatedTimestamp();
  /**
   * <pre>
   * This field is updated to be the current time periodically, and is also set
   * to the current time whenever another field changes. By examining the
   * difference between this field and the current time, it should be possible
   * to reason about the inactivity of any device that was syncing at one time.
   * </pre>
   *
   * <code>optional int64 last_updated_timestamp = 8;</code>
   * @return The lastUpdatedTimestamp.
   */
  long getLastUpdatedTimestamp();

  /**
   * <pre>
   * Device info fields that are specific to a feature. This is information that
   * can not be derived from the other fields in the proto and are not general
   * enough to be used by another feature.
   * </pre>
   *
   * <code>optional .sync_pb.FeatureSpecificFields feature_fields = 9;</code>
   * @return Whether the featureFields field is set.
   */
  boolean hasFeatureFields();
  /**
   * <pre>
   * Device info fields that are specific to a feature. This is information that
   * can not be derived from the other fields in the proto and are not general
   * enough to be used by another feature.
   * </pre>
   *
   * <code>optional .sync_pb.FeatureSpecificFields feature_fields = 9;</code>
   * @return The featureFields.
   */
  org.chromium.components.sync.protocol.FeatureSpecificFields getFeatureFields();

  /**
   * <pre>
   * Device specific information for Sharing feature.
   * </pre>
   *
   * <code>optional .sync_pb.SharingSpecificFields sharing_fields = 10;</code>
   * @return Whether the sharingFields field is set.
   */
  boolean hasSharingFields();
  /**
   * <pre>
   * Device specific information for Sharing feature.
   * </pre>
   *
   * <code>optional .sync_pb.SharingSpecificFields sharing_fields = 10;</code>
   * @return The sharingFields.
   */
  org.chromium.components.sync.protocol.SharingSpecificFields getSharingFields();

  /**
   * <pre>
   * Model of device.
   * </pre>
   *
   * <code>optional string model = 11;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <pre>
   * Model of device.
   * </pre>
   *
   * <code>optional string model = 11;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <pre>
   * Model of device.
   * </pre>
   *
   * <code>optional string model = 11;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * Name of device manufacturer.
   * </pre>
   *
   * <code>optional string manufacturer = 12;</code>
   * @return Whether the manufacturer field is set.
   */
  boolean hasManufacturer();
  /**
   * <pre>
   * Name of device manufacturer.
   * </pre>
   *
   * <code>optional string manufacturer = 12;</code>
   * @return The manufacturer.
   */
  java.lang.String getManufacturer();
  /**
   * <pre>
   * Name of device manufacturer.
   * </pre>
   *
   * <code>optional string manufacturer = 12;</code>
   * @return The bytes for manufacturer.
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <pre>
   * The interval in minutes with which |last_updated_timestamp| is updated to
   * the sync servers if online and while sync is actively running (e.g.
   * excludes backgrounded apps on Android). Introduced in M81. The legacy
   * default was 1 day.
   * </pre>
   *
   * <code>optional int32 pulse_interval_in_minutes = 13;</code>
   * @return Whether the pulseIntervalInMinutes field is set.
   */
  boolean hasPulseIntervalInMinutes();
  /**
   * <pre>
   * The interval in minutes with which |last_updated_timestamp| is updated to
   * the sync servers if online and while sync is actively running (e.g.
   * excludes backgrounded apps on Android). Introduced in M81. The legacy
   * default was 1 day.
   * </pre>
   *
   * <code>optional int32 pulse_interval_in_minutes = 13;</code>
   * @return The pulseIntervalInMinutes.
   */
  int getPulseIntervalInMinutes();

  /**
   * <pre>
   * Device specific information for Sync invalidations.
   * </pre>
   *
   * <code>optional .sync_pb.InvalidationSpecificFields invalidation_fields = 14;</code>
   * @return Whether the invalidationFields field is set.
   */
  boolean hasInvalidationFields();
  /**
   * <pre>
   * Device specific information for Sync invalidations.
   * </pre>
   *
   * <code>optional .sync_pb.InvalidationSpecificFields invalidation_fields = 14;</code>
   * @return The invalidationFields.
   */
  org.chromium.components.sync.protocol.InvalidationSpecificFields getInvalidationFields();

  /**
   * <pre>
   * Information for contacting this device in order to perform security key
   * operations.
   * </pre>
   *
   * <code>optional .sync_pb.PhoneAsASecurityKeySpecificFields paask_fields = 15;</code>
   * @return Whether the paaskFields field is set.
   */
  boolean hasPaaskFields();
  /**
   * <pre>
   * Information for contacting this device in order to perform security key
   * operations.
   * </pre>
   *
   * <code>optional .sync_pb.PhoneAsASecurityKeySpecificFields paask_fields = 15;</code>
   * @return The paaskFields.
   */
  org.chromium.components.sync.protocol.PhoneAsASecurityKeySpecificFields getPaaskFields();

  /**
   * <pre>
   * Unique hardware identifier string which details the HW combination of
   * a ChromeOS device. This field will be empty on other OS devices.
   * </pre>
   *
   * <code>optional string full_hardware_class = 16;</code>
   * @return Whether the fullHardwareClass field is set.
   */
  boolean hasFullHardwareClass();
  /**
   * <pre>
   * Unique hardware identifier string which details the HW combination of
   * a ChromeOS device. This field will be empty on other OS devices.
   * </pre>
   *
   * <code>optional string full_hardware_class = 16;</code>
   * @return The fullHardwareClass.
   */
  java.lang.String getFullHardwareClass();
  /**
   * <pre>
   * Unique hardware identifier string which details the HW combination of
   * a ChromeOS device. This field will be empty on other OS devices.
   * </pre>
   *
   * <code>optional string full_hardware_class = 16;</code>
   * @return The bytes for fullHardwareClass.
   */
  com.google.protobuf.ByteString
      getFullHardwareClassBytes();

  /**
   * <code>.sync_pb.ChromeVersionInfo chrome_version_info = 17;</code>
   * @return Whether the chromeVersionInfo field is set.
   */
  boolean hasChromeVersionInfo();
  /**
   * <code>.sync_pb.ChromeVersionInfo chrome_version_info = 17;</code>
   * @return The chromeVersionInfo.
   */
  org.chromium.components.sync.protocol.ChromeVersionInfo getChromeVersionInfo();

  /**
   * <code>.sync_pb.GooglePlayServicesVersionInfo google_play_services_version_info = 18;</code>
   * @return Whether the googlePlayServicesVersionInfo field is set.
   */
  boolean hasGooglePlayServicesVersionInfo();
  /**
   * <code>.sync_pb.GooglePlayServicesVersionInfo google_play_services_version_info = 18;</code>
   * @return The googlePlayServicesVersionInfo.
   */
  org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo getGooglePlayServicesVersionInfo();

  public org.chromium.components.sync.protocol.DeviceInfoSpecifics.ClientVersionInfoCase getClientVersionInfoCase();
}
