// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/entity_specifics.proto

package org.chromium.components.sync.protocol;

public interface EmptySpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.EmptySpecifics)
    com.google.protobuf.MessageLiteOrBuilder {
}
