// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/entity_specifics.proto

package org.chromium.components.sync.protocol;

public final class EntitySpecificsOuterClass {
  private EntitySpecificsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
