// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/device_info_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * Protobuf type {@code sync_pb.GooglePlayServicesVersionInfo}
 */
public  final class GooglePlayServicesVersionInfo extends
    com.google.protobuf.GeneratedMessageLite<
        GooglePlayServicesVersionInfo, GooglePlayServicesVersionInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.GooglePlayServicesVersionInfo)
    GooglePlayServicesVersionInfoOrBuilder {
  private GooglePlayServicesVersionInfo() {
    apkVersionName_ = "";
  }
  private int bitField0_;
  public static final int APK_VERSION_NAME_FIELD_NUMBER = 1;
  private java.lang.String apkVersionName_;
  /**
   * <code>optional string apk_version_name = 1;</code>
   * @return Whether the apkVersionName field is set.
   */
  @java.lang.Override
  public boolean hasApkVersionName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string apk_version_name = 1;</code>
   * @return The apkVersionName.
   */
  @java.lang.Override
  public java.lang.String getApkVersionName() {
    return apkVersionName_;
  }
  /**
   * <code>optional string apk_version_name = 1;</code>
   * @return The bytes for apkVersionName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApkVersionNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(apkVersionName_);
  }
  /**
   * <code>optional string apk_version_name = 1;</code>
   * @param value The apkVersionName to set.
   */
  private void setApkVersionName(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000001;
    apkVersionName_ = value;
  }
  /**
   * <code>optional string apk_version_name = 1;</code>
   */
  private void clearApkVersionName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    apkVersionName_ = getDefaultInstance().getApkVersionName();
  }
  /**
   * <code>optional string apk_version_name = 1;</code>
   * @param value The bytes for apkVersionName to set.
   */
  private void setApkVersionNameBytes(
      com.google.protobuf.ByteString value) {
    apkVersionName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sync_pb.GooglePlayServicesVersionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.GooglePlayServicesVersionInfo)
      org.chromium.components.sync.protocol.GooglePlayServicesVersionInfoOrBuilder {
    // Construct using org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string apk_version_name = 1;</code>
     * @return Whether the apkVersionName field is set.
     */
    @java.lang.Override
    public boolean hasApkVersionName() {
      return instance.hasApkVersionName();
    }
    /**
     * <code>optional string apk_version_name = 1;</code>
     * @return The apkVersionName.
     */
    @java.lang.Override
    public java.lang.String getApkVersionName() {
      return instance.getApkVersionName();
    }
    /**
     * <code>optional string apk_version_name = 1;</code>
     * @return The bytes for apkVersionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApkVersionNameBytes() {
      return instance.getApkVersionNameBytes();
    }
    /**
     * <code>optional string apk_version_name = 1;</code>
     * @param value The apkVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setApkVersionName(
        java.lang.String value) {
      copyOnWrite();
      instance.setApkVersionName(value);
      return this;
    }
    /**
     * <code>optional string apk_version_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearApkVersionName() {
      copyOnWrite();
      instance.clearApkVersionName();
      return this;
    }
    /**
     * <code>optional string apk_version_name = 1;</code>
     * @param value The bytes for apkVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setApkVersionNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApkVersionNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.GooglePlayServicesVersionInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "apkVersionName_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1008\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.GooglePlayServicesVersionInfo)
  private static final org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo DEFAULT_INSTANCE;
  static {
    GooglePlayServicesVersionInfo defaultInstance = new GooglePlayServicesVersionInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GooglePlayServicesVersionInfo.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.GooglePlayServicesVersionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GooglePlayServicesVersionInfo> PARSER;

  public static com.google.protobuf.Parser<GooglePlayServicesVersionInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

