// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/history_specifics.proto

package org.chromium.components.sync.protocol;

public interface HistorySpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.HistorySpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Timestamp, also called "global ID" in some places (e.g. in delete
   * directives). This uniquely identifies the entity.
   * </pre>
   *
   * <code>optional int64 visit_time_windows_epoch_micros = 1;</code>
   * @return Whether the visitTimeWindowsEpochMicros field is set.
   */
  boolean hasVisitTimeWindowsEpochMicros();
  /**
   * <pre>
   * Timestamp, also called "global ID" in some places (e.g. in delete
   * directives). This uniquely identifies the entity.
   * </pre>
   *
   * <code>optional int64 visit_time_windows_epoch_micros = 1;</code>
   * @return The visitTimeWindowsEpochMicros.
   */
  long getVisitTimeWindowsEpochMicros();

  /**
   * <pre>
   * Cache GUID of the client that produced this entity, aka the "originator".
   * </pre>
   *
   * <code>optional string originator_cache_guid = 2;</code>
   * @return Whether the originatorCacheGuid field is set.
   */
  boolean hasOriginatorCacheGuid();
  /**
   * <pre>
   * Cache GUID of the client that produced this entity, aka the "originator".
   * </pre>
   *
   * <code>optional string originator_cache_guid = 2;</code>
   * @return The originatorCacheGuid.
   */
  java.lang.String getOriginatorCacheGuid();
  /**
   * <pre>
   * Cache GUID of the client that produced this entity, aka the "originator".
   * </pre>
   *
   * <code>optional string originator_cache_guid = 2;</code>
   * @return The bytes for originatorCacheGuid.
   */
  com.google.protobuf.ByteString
      getOriginatorCacheGuidBytes();

  /**
   * <pre>
   * The redirect chain. The first entry is the URL the user originally
   * navigated to; the last one is where they ended up. If there were no
   * redirects, this has only one entry.
   * </pre>
   *
   * <code>repeated .sync_pb.HistorySpecifics.RedirectEntry redirect_entries = 3;</code>
   */
  java.util.List<org.chromium.components.sync.protocol.HistorySpecifics.RedirectEntry> 
      getRedirectEntriesList();
  /**
   * <pre>
   * The redirect chain. The first entry is the URL the user originally
   * navigated to; the last one is where they ended up. If there were no
   * redirects, this has only one entry.
   * </pre>
   *
   * <code>repeated .sync_pb.HistorySpecifics.RedirectEntry redirect_entries = 3;</code>
   */
  org.chromium.components.sync.protocol.HistorySpecifics.RedirectEntry getRedirectEntries(int index);
  /**
   * <pre>
   * The redirect chain. The first entry is the URL the user originally
   * navigated to; the last one is where they ended up. If there were no
   * redirects, this has only one entry.
   * </pre>
   *
   * <code>repeated .sync_pb.HistorySpecifics.RedirectEntry redirect_entries = 3;</code>
   */
  int getRedirectEntriesCount();

  /**
   * <pre>
   * The PageTransition for the navigation.
   * </pre>
   *
   * <code>optional .sync_pb.HistorySpecifics.PageTransition page_transition = 4;</code>
   * @return Whether the pageTransition field is set.
   */
  boolean hasPageTransition();
  /**
   * <pre>
   * The PageTransition for the navigation.
   * </pre>
   *
   * <code>optional .sync_pb.HistorySpecifics.PageTransition page_transition = 4;</code>
   * @return The pageTransition.
   */
  org.chromium.components.sync.protocol.HistorySpecifics.PageTransition getPageTransition();

  /**
   * <pre>
   * The ID of the visit, on the originator client, that was a referrer for
   * this one, or 0 if no referrer exists.
   * </pre>
   *
   * <code>optional int64 originator_referring_visit_id = 5;</code>
   * @return Whether the originatorReferringVisitId field is set.
   */
  boolean hasOriginatorReferringVisitId();
  /**
   * <pre>
   * The ID of the visit, on the originator client, that was a referrer for
   * this one, or 0 if no referrer exists.
   * </pre>
   *
   * <code>optional int64 originator_referring_visit_id = 5;</code>
   * @return The originatorReferringVisitId.
   */
  long getOriginatorReferringVisitId();

  /**
   * <pre>
   * The ID of the visit, on the originator client, that opened this one, or 0
   * if no opener exists.
   * </pre>
   *
   * <code>optional int64 originator_opener_visit_id = 6;</code>
   * @return Whether the originatorOpenerVisitId field is set.
   */
  boolean hasOriginatorOpenerVisitId();
  /**
   * <pre>
   * The ID of the visit, on the originator client, that opened this one, or 0
   * if no opener exists.
   * </pre>
   *
   * <code>optional int64 originator_opener_visit_id = 6;</code>
   * @return The originatorOpenerVisitId.
   */
  long getOriginatorOpenerVisitId();

  /**
   * <pre>
   * The duration of the visit, in microseconds. Zero if the visit hasn't been
   * finished (or the duration wasn't updated for some other reason).
   * </pre>
   *
   * <code>optional int64 visit_duration_micros = 7;</code>
   * @return Whether the visitDurationMicros field is set.
   */
  boolean hasVisitDurationMicros();
  /**
   * <pre>
   * The duration of the visit, in microseconds. Zero if the visit hasn't been
   * finished (or the duration wasn't updated for some other reason).
   * </pre>
   *
   * <code>optional int64 visit_duration_micros = 7;</code>
   * @return The visitDurationMicros.
   */
  long getVisitDurationMicros();
}
