// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/printers_authorization_server_specifics.proto

package org.chromium.components.sync.protocol;

public interface PrintersAuthorizationServerSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.PrintersAuthorizationServerSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Universal Resource Identifier for the authorization server on the network.
   * The scheme must be https. Example: https://address.example:port/path/path.
   * This field must be unique and is required.
   * </pre>
   *
   * <code>optional string uri = 1;</code>
   * @return Whether the uri field is set.
   */
  boolean hasUri();
  /**
   * <pre>
   * Universal Resource Identifier for the authorization server on the network.
   * The scheme must be https. Example: https://address.example:port/path/path.
   * This field must be unique and is required.
   * </pre>
   *
   * <code>optional string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * Universal Resource Identifier for the authorization server on the network.
   * The scheme must be https. Example: https://address.example:port/path/path.
   * This field must be unique and is required.
   * </pre>
   *
   * <code>optional string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();
}
