// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/vault.proto

package org.chromium.components.sync.protocol;

public interface RPCStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.RPCStatus)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  java.util.List<org.chromium.components.sync.protocol.Proto3Any> 
      getDetailsList();
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  org.chromium.components.sync.protocol.Proto3Any getDetails(int index);
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  int getDetailsCount();
}
