// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/vault.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Forked version of google.rpc.Status.
 * </pre>
 *
 * Protobuf type {@code sync_pb.RPCStatus}
 */
public  final class RPCStatus extends
    com.google.protobuf.GeneratedMessageLite<
        RPCStatus, RPCStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.RPCStatus)
    RPCStatusOrBuilder {
  private RPCStatus() {
    details_ = emptyProtobufList();
  }
  public static final int DETAILS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<org.chromium.components.sync.protocol.Proto3Any> details_;
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.chromium.components.sync.protocol.Proto3Any> getDetailsList() {
    return details_;
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  public java.util.List<? extends org.chromium.components.sync.protocol.Proto3AnyOrBuilder> 
      getDetailsOrBuilderList() {
    return details_;
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  @java.lang.Override
  public int getDetailsCount() {
    return details_.size();
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  @java.lang.Override
  public org.chromium.components.sync.protocol.Proto3Any getDetails(int index) {
    return details_.get(index);
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  public org.chromium.components.sync.protocol.Proto3AnyOrBuilder getDetailsOrBuilder(
      int index) {
    return details_.get(index);
  }
  private void ensureDetailsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.chromium.components.sync.protocol.Proto3Any> tmp = details_;
    if (!tmp.isModifiable()) {
      details_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void setDetails(
      int index, org.chromium.components.sync.protocol.Proto3Any value) {
    value.getClass();
  ensureDetailsIsMutable();
    details_.set(index, value);
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void addDetails(org.chromium.components.sync.protocol.Proto3Any value) {
    value.getClass();
  ensureDetailsIsMutable();
    details_.add(value);
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void addDetails(
      int index, org.chromium.components.sync.protocol.Proto3Any value) {
    value.getClass();
  ensureDetailsIsMutable();
    details_.add(index, value);
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void addAllDetails(
      java.lang.Iterable<? extends org.chromium.components.sync.protocol.Proto3Any> values) {
    ensureDetailsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, details_);
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void clearDetails() {
    details_ = emptyProtobufList();
  }
  /**
   * <code>repeated .sync_pb.Proto3Any details = 3;</code>
   */
  private void removeDetails(int index) {
    ensureDetailsIsMutable();
    details_.remove(index);
  }

  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.RPCStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.RPCStatus prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Forked version of google.rpc.Status.
   * </pre>
   *
   * Protobuf type {@code sync_pb.RPCStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.RPCStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.RPCStatus)
      org.chromium.components.sync.protocol.RPCStatusOrBuilder {
    // Construct using org.chromium.components.sync.protocol.RPCStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.chromium.components.sync.protocol.Proto3Any> getDetailsList() {
      return java.util.Collections.unmodifiableList(
          instance.getDetailsList());
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    @java.lang.Override
    public int getDetailsCount() {
      return instance.getDetailsCount();
    }/**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    @java.lang.Override
    public org.chromium.components.sync.protocol.Proto3Any getDetails(int index) {
      return instance.getDetails(index);
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder setDetails(
        int index, org.chromium.components.sync.protocol.Proto3Any value) {
      copyOnWrite();
      instance.setDetails(index, value);
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder setDetails(
        int index, org.chromium.components.sync.protocol.Proto3Any.Builder builderForValue) {
      copyOnWrite();
      instance.setDetails(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder addDetails(org.chromium.components.sync.protocol.Proto3Any value) {
      copyOnWrite();
      instance.addDetails(value);
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder addDetails(
        int index, org.chromium.components.sync.protocol.Proto3Any value) {
      copyOnWrite();
      instance.addDetails(index, value);
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder addDetails(
        org.chromium.components.sync.protocol.Proto3Any.Builder builderForValue) {
      copyOnWrite();
      instance.addDetails(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder addDetails(
        int index, org.chromium.components.sync.protocol.Proto3Any.Builder builderForValue) {
      copyOnWrite();
      instance.addDetails(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder addAllDetails(
        java.lang.Iterable<? extends org.chromium.components.sync.protocol.Proto3Any> values) {
      copyOnWrite();
      instance.addAllDetails(values);
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder clearDetails() {
      copyOnWrite();
      instance.clearDetails();
      return this;
    }
    /**
     * <code>repeated .sync_pb.Proto3Any details = 3;</code>
     */
    public Builder removeDetails(int index) {
      copyOnWrite();
      instance.removeDetails(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.RPCStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.RPCStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "details_",
            org.chromium.components.sync.protocol.Proto3Any.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0003\u0003\u0001\u0000\u0001\u0000\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.RPCStatus> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.RPCStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.RPCStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.RPCStatus)
  private static final org.chromium.components.sync.protocol.RPCStatus DEFAULT_INSTANCE;
  static {
    RPCStatus defaultInstance = new RPCStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RPCStatus.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.RPCStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RPCStatus> PARSER;

  public static com.google.protobuf.Parser<RPCStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

