// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/vault.proto

package org.chromium.components.sync.protocol;

/**
 * Protobuf type {@code sync_pb.SecurityDomainDetails}
 */
public  final class SecurityDomainDetails extends
    com.google.protobuf.GeneratedMessageLite<
        SecurityDomainDetails, SecurityDomainDetails.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.SecurityDomainDetails)
    SecurityDomainDetailsOrBuilder {
  private SecurityDomainDetails() {
  }
  public interface SyncDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sync_pb.SecurityDomainDetails.SyncDetails)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool degraded_recoverability = 1;</code>
     * @return The degradedRecoverability.
     */
    boolean getDegradedRecoverability();
  }
  /**
   * Protobuf type {@code sync_pb.SecurityDomainDetails.SyncDetails}
   */
  public  static final class SyncDetails extends
      com.google.protobuf.GeneratedMessageLite<
          SyncDetails, SyncDetails.Builder> implements
      // @@protoc_insertion_point(message_implements:sync_pb.SecurityDomainDetails.SyncDetails)
      SyncDetailsOrBuilder {
    private SyncDetails() {
    }
    public static final int DEGRADED_RECOVERABILITY_FIELD_NUMBER = 1;
    private boolean degradedRecoverability_;
    /**
     * <code>bool degraded_recoverability = 1;</code>
     * @return The degradedRecoverability.
     */
    @java.lang.Override
    public boolean getDegradedRecoverability() {
      return degradedRecoverability_;
    }
    /**
     * <code>bool degraded_recoverability = 1;</code>
     * @param value The degradedRecoverability to set.
     */
    private void setDegradedRecoverability(boolean value) {
      
      degradedRecoverability_ = value;
    }
    /**
     * <code>bool degraded_recoverability = 1;</code>
     */
    private void clearDegradedRecoverability() {
      
      degradedRecoverability_ = false;
    }

    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code sync_pb.SecurityDomainDetails.SyncDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails, Builder> implements
        // @@protoc_insertion_point(builder_implements:sync_pb.SecurityDomainDetails.SyncDetails)
        org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetailsOrBuilder {
      // Construct using org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool degraded_recoverability = 1;</code>
       * @return The degradedRecoverability.
       */
      @java.lang.Override
      public boolean getDegradedRecoverability() {
        return instance.getDegradedRecoverability();
      }
      /**
       * <code>bool degraded_recoverability = 1;</code>
       * @param value The degradedRecoverability to set.
       * @return This builder for chaining.
       */
      public Builder setDegradedRecoverability(boolean value) {
        copyOnWrite();
        instance.setDegradedRecoverability(value);
        return this;
      }
      /**
       * <code>bool degraded_recoverability = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDegradedRecoverability() {
        copyOnWrite();
        instance.clearDegradedRecoverability();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sync_pb.SecurityDomainDetails.SyncDetails)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "degradedRecoverability_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:sync_pb.SecurityDomainDetails.SyncDetails)
    private static final org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails DEFAULT_INSTANCE;
    static {
      SyncDetails defaultInstance = new SyncDetails();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SyncDetails.class, defaultInstance);
    }

    public static org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SyncDetails> PARSER;

    public static com.google.protobuf.Parser<SyncDetails> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int SYNC_DETAILS_FIELD_NUMBER = 1;
  private org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails syncDetails_;
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   */
  @java.lang.Override
  public boolean hasSyncDetails() {
    return syncDetails_ != null;
  }
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   */
  @java.lang.Override
  public org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails getSyncDetails() {
    return syncDetails_ == null ? org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.getDefaultInstance() : syncDetails_;
  }
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   */
  private void setSyncDetails(org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails value) {
    value.getClass();
  syncDetails_ = value;
    
    }
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSyncDetails(org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails value) {
    value.getClass();
  if (syncDetails_ != null &&
        syncDetails_ != org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.getDefaultInstance()) {
      syncDetails_ =
        org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.newBuilder(syncDetails_).mergeFrom(value).buildPartial();
    } else {
      syncDetails_ = value;
    }
    
  }
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   */
  private void clearSyncDetails() {  syncDetails_ = null;
    
  }

  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.SecurityDomainDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.SecurityDomainDetails prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sync_pb.SecurityDomainDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.SecurityDomainDetails, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.SecurityDomainDetails)
      org.chromium.components.sync.protocol.SecurityDomainDetailsOrBuilder {
    // Construct using org.chromium.components.sync.protocol.SecurityDomainDetails.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    @java.lang.Override
    public boolean hasSyncDetails() {
      return instance.hasSyncDetails();
    }
    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    @java.lang.Override
    public org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails getSyncDetails() {
      return instance.getSyncDetails();
    }
    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    public Builder setSyncDetails(org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails value) {
      copyOnWrite();
      instance.setSyncDetails(value);
      return this;
      }
    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    public Builder setSyncDetails(
        org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails.Builder builderForValue) {
      copyOnWrite();
      instance.setSyncDetails(builderForValue.build());
      return this;
    }
    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    public Builder mergeSyncDetails(org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails value) {
      copyOnWrite();
      instance.mergeSyncDetails(value);
      return this;
    }
    /**
     * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
     */
    public Builder clearSyncDetails() {  copyOnWrite();
      instance.clearSyncDetails();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.SecurityDomainDetails)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.SecurityDomainDetails();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "syncDetails_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.SecurityDomainDetails> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.SecurityDomainDetails.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.SecurityDomainDetails>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.SecurityDomainDetails)
  private static final org.chromium.components.sync.protocol.SecurityDomainDetails DEFAULT_INSTANCE;
  static {
    SecurityDomainDetails defaultInstance = new SecurityDomainDetails();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SecurityDomainDetails.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.SecurityDomainDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SecurityDomainDetails> PARSER;

  public static com.google.protobuf.Parser<SecurityDomainDetails> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

