// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/vault.proto

package org.chromium.components.sync.protocol;

public interface SecurityDomainDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.SecurityDomainDetails)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   * @return Whether the syncDetails field is set.
   */
  boolean hasSyncDetails();
  /**
   * <code>.sync_pb.SecurityDomainDetails.SyncDetails sync_details = 1;</code>
   * @return The syncDetails.
   */
  org.chromium.components.sync.protocol.SecurityDomainDetails.SyncDetails getSyncDetails();
}
