// services/network/public/mojom/devtools_observer.mojom-shared-message-ids.h is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SERVICES_NETWORK_PUBLIC_MOJOM_DEVTOOLS_OBSERVER_MOJOM_SHARED_MESSAGE_IDS_H_
#define SERVICES_NETWORK_PUBLIC_MOJOM_DEVTOOLS_OBSERVER_MOJOM_SHARED_MESSAGE_IDS_H_

#include <stdint.h>
namespace network {
namespace mojom {

namespace internal {


constexpr uint32_t kDevToolsObserver_OnRawRequest_Name = 0;
constexpr uint32_t kDevToolsObserver_OnRawResponse_Name = 1;
constexpr uint32_t kDevToolsObserver_OnPrivateNetworkRequest_Name = 2;
constexpr uint32_t kDevToolsObserver_OnCorsPreflightRequest_Name = 3;
constexpr uint32_t kDevToolsObserver_OnCorsPreflightResponse_Name = 4;
constexpr uint32_t kDevToolsObserver_OnCorsPreflightRequestCompleted_Name = 5;
constexpr uint32_t kDevToolsObserver_OnTrustTokenOperationDone_Name = 6;
constexpr uint32_t kDevToolsObserver_OnCorsError_Name = 7;
constexpr uint32_t kDevToolsObserver_OnSubresourceWebBundleMetadata_Name = 8;
constexpr uint32_t kDevToolsObserver_OnSubresourceWebBundleMetadataError_Name = 9;
constexpr uint32_t kDevToolsObserver_OnSubresourceWebBundleInnerResponse_Name = 10;
constexpr uint32_t kDevToolsObserver_OnSubresourceWebBundleInnerResponseError_Name = 11;
constexpr uint32_t kDevToolsObserver_Clone_Name = 12;

}  // namespace internal
}  // namespace mojom
}  // namespace network

#endif  // SERVICES_NETWORK_PUBLIC_MOJOM_DEVTOOLS_OBSERVER_MOJOM_SHARED_MESSAGE_IDS_H_